<?php

use Illuminate\Database\Seeder;

// composer require laracasts/testdummy
use Laracasts\TestDummy\Factory as TestDummy;

class FornecedorSeeder extends Seeder
{
    public function run()
    {
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '162.614.532-68', 'nome' => 'TEREZINHA RODRIGUES VIANA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '210.849.396-49', 'nome' => 'LUIZ CARLOS DE OLIVEIRA MAIA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '203.437.014-72', 'nome' => 'TOMAS SILVEIRA GUIMARAES']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '658.175.406-49', 'nome' => 'BERNADETE MARIA FRANCO DA ROSA FREIRE']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '172.524.584-15', 'nome' => 'SONIA LEMOS COSTA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '397.292.309-00', 'nome' => 'ILDA MARTINS RAHAL']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '234.672.310-04', 'nome' => 'ELAINE TEREZINHA WERLE']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '376.203.046-49', 'nome' => 'MARIA BEATRIZ BATISTA DE SIQUEIRA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '045.804.863-15', 'nome' => 'CIRO BELCHIOR ROCHA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '049.836.537-91', 'nome' => 'JOSE EDSON AYRES DE ALMEIDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '050.138.458-82', 'nome' => 'JORGE FELIPE ISPER']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '847.272.338-00', 'nome' => 'CARLOS MAGNO RABELO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '277.172.165-15', 'nome' => 'DORIVAL DE AMORIM LEITE JUNIOR']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '062.040.058-71', 'nome' => 'CRISTINA BOULHOSA FABRIS FERREIRA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '249.602.332-49', 'nome' => 'FARID ANTÓNIO RAAD MASSOUD,']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '026.569.148-68', 'nome' => 'JOÃO DIB']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '133.431.905-78', 'nome' => 'ALVINO NOGUEIRA DE CARVALHO JUNIOR']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '816.799.557-72', 'nome' => 'TATIANA MELO TORRES']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '131.926.479-49', 'nome' => 'OENES NECKEL DE MENEZES']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '395.016.678-55', 'nome' => 'JOSÉ PAULO PIMENTEL NACCARATO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '347.068.106-63', 'nome' => 'MARCELO MARIGO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '177.454.620-53', 'nome' => 'JOSE AUGUSTO MARCON']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'FISICA', 'cpf_cnpj_idgener' => '123.012.132-34', 'nome' => 'MARIA ISABEL DA SILVA PIRES SOARES']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'IDGENERICO', 'cpf_cnpj_idgener' => 'EX5110161', 'nome' => 'MAYER BROWN LLP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'IDGENERICO', 'cpf_cnpj_idgener' => 'EX4110161', 'nome' => 'STUDIO GENTILONI SILVERI DIRITTO PENALE']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'IDGENERICO', 'cpf_cnpj_idgener' => 'EX9110161', 'nome' => 'BERETTA GODOY']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'IDGENERICO', 'cpf_cnpj_idgener' => 'EX1210161', 'nome' => 'SÉRGIO MOTA & ASSOCIADOS SOCIEDADE DE ADVOGADOS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'IDGENERICO', 'cpf_cnpj_idgener' => 'EX7110161', 'nome' => 'GOMEZ Y ASOCIADOS ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'IDGENERICO', 'cpf_cnpj_idgener' => 'EX195FORT', 'nome' => 'ARNOLD & PORTER LLP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'IDGENERICO', 'cpf_cnpj_idgener' => 'EX1010161', 'nome' => 'RSA SOCIEDADE DE ADVOGADOS ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'IDGENERICO', 'cpf_cnpj_idgener' => 'EX2110161', 'nome' => 'CHIOMENTI STUDIO LEGALE']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'IDGENERICO', 'cpf_cnpj_idgener' => 'EX1310161', 'nome' => 'CURBELO ABOGADOS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.618.334/0001-72', 'nome' => 'SÉTIMA SERVIÇOS DE LIMPEZA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.234.788/0001-99', 'nome' => 'FINANCIAL IMOBILIÁRIA LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.858.667/0001-79', 'nome' => 'MR INVESTIMENTOS S/A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.000.028/0001-29', 'nome' => 'TARGET ENGENHARIA E CONSULTORIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.161.111/0001-42', 'nome' => 'MONTE BELO EMPREENDIMENTOS IMOB. LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.621.952/0001-34', 'nome' => 'RAPA LOCAÇÕES DE IMÓVEIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.233.652/0001-90', 'nome' => 'SETE SATÉLITE SERVIÇOS TERCEIRIZADOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.500.126/0001-49', 'nome' => 'FETRANSCOOP MG FED DAS COOPERATIVAS DE TRANSPORTE DE CARGAS E PASSAGEIROS DO ESTADO DE MINAS GERAIS ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.534.028/0001-05', 'nome' => 'CATA VENTO REFRIGERAÇÕES E SERVIÇOS GERAIS LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '34.028.316/0007-07', 'nome' => 'EMPRESA BRASILEIRA DE CORREIOS E TELEGRAFOS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.350.057/0001-71', 'nome' => 'S & M CONSERVAÇÃO E LIMPEZA LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '81.547.614/0001-90', 'nome' => 'GIACOMELLI IMÓVEIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.332.087/0005-28', 'nome' => 'SECURITY VIGILÂNCIA E SEGURANÇA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.054.815/0001-70', 'nome' => 'ADS SERVIÇOS DE LOCAÇÃO DE MAO DE OBRA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.392.445/0001-67', 'nome' => 'CRIVELIN LOCAÇÃO DE IMÓVEIS E PARTICIPAÇÕES LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '34.513.622/0001-35', 'nome' => 'HIGINO SORDI SOUSA TOLEDANO E ADVOGADOS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.020.874/0001-50', 'nome' => 'JPN EMPREENDIMENTOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.926.223/0001-60', 'nome' => 'AMÉRICA TECNOLOGIA DE INFORMÁTICA E ELETROELETRÔNICOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.310.925/0001-88', 'nome' => 'ATHUS CONSTRUÇÕES E SERVIÇOS LTDA - EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '87.215.299/0001-80', 'nome' => 'TELEALARME BRASIL LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.323.090/0001-51', 'nome' => 'SOLL SERVIÇOS OBRAS E LOCAÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '84.968.874/0001-27', 'nome' => 'ALMAQ EQUIPAMENTOS PARA ESCRITÓRIO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.558.157/0001-62', 'nome' => 'TELEFÔNICA BRASIL S/A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.188.695/0001-66', 'nome' => 'ANTONIO J. DOS SANTOS MANUTENÇÃO E REFORMAS  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '79.894.168/0001-48', 'nome' => 'VIGILANCIA TRIANGULO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.166.512/0001-49', 'nome' => 'DDS GESTORA DE ATIVOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.016.439/0001-38', 'nome' => 'RIO GRANDE ENEGIA SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.341.467/0001-20', 'nome' => 'AMAZONAS ENERGIA S.A ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.426.962/0001-60', 'nome' => 'DW REFRIGERAÇÃO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.105.598/0001-71', 'nome' => 'D.E REBOUÇAS EIRELI - EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.969.071/0001-10', 'nome' => 'APPA SERVIÇOS TEMPORARIOS E EFETIVOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.650.833/0001-23', 'nome' => 'POLO SEGURANÇA ESPECIALIZADA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.222.747/0001-94', 'nome' => 'GABRIELA CENTER LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.891.176/0001-06', 'nome' => 'SOBERANA TERCEIRIZAÇÃO DE SERVIÇOS EIRELI  IME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.028.986/0011-80', 'nome' => 'ELEVADORES ATLAS SCHINDLER SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.172.237/0001-24', 'nome' => 'D&L SERVIÇOS DE APOIO ADMINISTRATIVO LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.566.846/0001-03', 'nome' => 'CONSTRUTORA HEMA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '83.779.462/0001-86', 'nome' => 'SAMAE  SERVIÇO AUTÔNOMO MUNICIPAL DE ÁGUA E ESGOTO DE BLUMENAU  ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '66.748.955/0001-30', 'nome' => 'ALMEIDA SAPATA ENGENHARIA E CONTRUÇÃO LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.992.117/0001-97', 'nome' => 'JH2P CONSTRUÇÕES E DECORAÇÃO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.938.116/0001-18', 'nome' => 'ANCAR - ADMINISTRADORES DE IMÓVEIS, DE CONDOMINIO E GESTÃO PECUNIÁRIA LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.422.562/0001-02', 'nome' => 'V3 SERVICES INFORMAÇÃO E CONSULTORIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '24.130.072/0001-11', 'nome' => 'TRIBUNAL REGIONAL FEDERAL 5 REGIAO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.332.087/0012-57', 'nome' => 'SECURITY VIGILÂNCIA E SEGURANÇA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.616.929/0001-02', 'nome' => 'SANEAGO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.432.517/0001-07', 'nome' => 'SIMPRESS - COMÉRCIO, LOCAÇÃO E SERVIÇOS S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.187.088/0001-41', 'nome' => 'DIAGONAL SERVIÇOS PROFISSINAIS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '90.778.978/0001-71', 'nome' => 'ZANATTA IMÓVEIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.708.745/0001-11', 'nome' => 'COOPERATIVA DOS PROPRIETÁRIOS DE TÁXI DE NATAL']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '26.989.350/0011-98', 'nome' => 'FUNASARN']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.836.848/0001-71', 'nome' => 'DIBASA COMÉRCIO E SERVIÇOS TÉCNICOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.467.321/0001-99', 'nome' => 'ENERGISA MATO GROSSO DO SUL  DISTRIBUIDORA DE ENERGIA SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '22.813.952/0001-67', 'nome' => 'LEXISNEXIS INFORMAÇÕES E SISTEMAS EMPRESARIAIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.019.295/0002-70', 'nome' => 'RG SEGURANÇA  E VIGILÃNCIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '57.049.793/0001-50', 'nome' => 'J. MOREIRA ADMINISTRAÇÃO E EQUIPAMENTOS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.089.570/0001-50', 'nome' => 'AGUAS GUARIROBA SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.926.785/0001-81', 'nome' => 'PRONTSERV PRESTAÇÃO DE SERVIÇOS DE LIMPEZA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '76.535.764/0001-43', 'nome' => 'OI S/A ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.340.639/0001-30', 'nome' => 'PRIME CONSULTORIA E ASSESSORIA EMPRESARIAL LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '92.610.187/0001-63', 'nome' => 'CONSTRU-ESSE EMPREENDIMENTOS IMOB.LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.765.290/0001-52', 'nome' => 'SERVICE ITORORÓ EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.221.915/0001-06', 'nome' => 'REINALDO GALVAO BELO DA SILVA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.229.363/0001-91', 'nome' => 'BETRON TECNOLOGIA EM SEGURANÇA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '92.514.801/0001-93', 'nome' => 'GRAZZIOTIN NEGÓCIOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '52.315.678/0001-67', 'nome' => 'RESIDEC CONTRUTORA E INCORPORADORA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.427.994/0001-40', 'nome' => 'LG ADMINISTRADORA DE SERVIÇOS EIRELI  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '86.688.785/0001-52', 'nome' => 'NEW SERVICE ADMINISTRAÇÃO E SERVIÇOS EIRELI ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '76.858.265/0001-97', 'nome' => 'IBIZA ADMINISTRAÇÃO DE BENS E PARTICIPAÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '52.061.181/0001-60', 'nome' => 'DEPARTAMENTO DE AGUA E ESGOTO DE MARILIA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.697.330/0001-64', 'nome' => 'MAR & MAR VEÍCULOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '90.347.840/0006-22', 'nome' => 'THYSSENKRUPP ELEVADORES S/A ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '20.692.899/0001-68', 'nome' => 'HRS EMPREENDIMENTOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.978.473/0001-20', 'nome' => 'AIRTEMP CENTRAL DE SERVIÇOS E COMÉRCIO DE REFRIGERAÇÃO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '61.198.164/0001-60', 'nome' => 'PORTO SEGURO COMPANHIA DE SEGUROS GERAIS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.660.263/0001-02', 'nome' => 'A & A CLIMATIZAÇÃO DE AMBIENTES  LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '14.724.076/0001-74', 'nome' => 'CONTEMPORANEA EMPREENDIMENTOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '87.743.613/0001-05', 'nome' => 'MITRA DIOCESANA DE RIO GRANDE']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.017.462/0001-63', 'nome' => 'ENERGISA SERGIPE DISTRIBUIDORA DE ENERGIA S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.491.163/0001-26', 'nome' => 'RIO MINAS TERCEIRIZAÇÃO E ADMINISTRAÇÃO DE SERVIÇOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.363.284/0001-06', 'nome' => 'EMPREENDIMENTOS TURÍSTICOS MAGALA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '33.000.118/0001-79', 'nome' => 'TELEMAR NORTE LESTE S/A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '20.861.259/0001-34', 'nome' => 'PROPENG ENGENHARIA E CONSULTORIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '76.371.103/0001-20', 'nome' => 'TELE ALARME SISTEMAS DE SEGURANÇA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '23.032.014/0001-92', 'nome' => 'TN NETO EIRELI EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '92.802.784/0001-90', 'nome' => 'CORSAN  COMPANHIA RIOGRANDENSE DE SANEAMENTO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '23.664.303/0001-04', 'nome' => 'DME DISTRIBUIÇÃO S A  DMED']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '25.086.034/0001-71', 'nome' => 'CELTINS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.389.269/0001-74', 'nome' => 'ALCTEL TELECOMUNICAÇÕES E INFORMÁTICA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '76.484.013/0001-45', 'nome' => 'COMPANHIA DE SANEAMENTO DO PARANA  SANEPAR']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.944.975/0001-29', 'nome' => 'PINHEIRO SEGURANÇA E VIGILANCIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.441.811/0001-03', 'nome' => 'SPE ITAIM PARTICIPAÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.522.669/0001-92', 'nome' => 'CEB DISTRIBUIÇÃO S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '41.769.803/0001-92', 'nome' => 'EDITORA FÓRUM ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.973.567/0001-68', 'nome' => 'TRINDADE DÁVILA CONSTRUTORA E INCORPORADORA LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '92.220.862/0001-48', 'nome' => 'SERVIÇO AUTONOMO DE SANEAMENTO DE PELOTAS  SANEP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.615.817/0002-22', 'nome' => 'FORTEVIP FORTE VIGILÂNCIA PRIVADA EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.503.775/0001-80', 'nome' => 'PIONEER EMPREENDIMENTOS COMERCIAIS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.487.259/0001-25', 'nome' => 'PORTAL DA AMAZÔNIA EMPREENDIMENTOS TURÍSTICOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '72.619.976/0001-58', 'nome' => 'ÁGIL-EMPRESA DE VIGILÂNCIA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '14.995.581/0001-53', 'nome' => 'CAB CUIABA SA CONCESSIONARIA DE SERVIÇOS PÚBLICOS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '20.616.722/0001-82', 'nome' => 'ARMAZÉM SÁ IMPORTAÇÃO E EXPORTAÇÃO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '46.119.855/0001-37', 'nome' => 'SOCIEDADE DE ABASTECIMENTO DE AGUA E SANEAMENTO SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.409.533/0001-82', 'nome' => 'CAVALCANTE & ESTEVES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.889.835/0001-20', 'nome' => 'PIERCOFFEE LOCAÇÕES E SERVIÇOS LTDAME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '78.766.151/0001-42', 'nome' => 'SIGMAFONE TELEC. LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '76.352.442/0001-69', 'nome' => 'TAM EMPREENDIMENTOS IMOB. LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.111.745/0001-77', 'nome' => 'TOP AR CONDICIONADO LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.895.728/0001-80', 'nome' => 'CENTRAIS ELÉTRICAS DO PARÁ SA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '14.667.684/0001-94', 'nome' => 'POLC EMPREENDIMENTOS, SERVIÇOS E COMÉRCIO LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.353.466/0001-12', 'nome' => 'RF EMPREENDIMENTOS IMOBILIÁRIOS 2011 LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.264.927/0001-27', 'nome' => 'MANAUS AMBIENTAL S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.563.494/0001-24', 'nome' => 'W & E SERVIÇOS TERCEIRIZADOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.266.746/0001-03', 'nome' => 'FERRAZ E FILHOS EMPREENDIMENTOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.324.196/0001-81', 'nome' => 'COMPANHIA ENERGÉTICA DO RIO GRANDE DO NORTE COSERN']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.082.024/0001-37', 'nome' => 'COMPANHIA DE SANEAMENTO AMBIENTAL DO DISTRITO FEDERAL']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '73.421.679/0001-66', 'nome' => 'ENGEPORTO ENGENHARIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.939.467/0001-15', 'nome' => 'CAER COMPANHIA DE ÁGUAS E ESGOTOS DE RORAIMA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '25.089.509/0001-83', 'nome' => 'SANEATINS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.699.029/0001-90', 'nome' => 'CANOPUS CONSTRUÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.945.341/0001-90', 'nome' => 'COMPANHIA DE SANEAMENTO DO PARÁ COSANPA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.165.068/0001-03', 'nome' => 'J. ATAIDE ALVES & CIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '61.007.647/0001-30', 'nome' => 'GOLD LAND EMPREENDIMENTOS IMOBILIÁRIOS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.153.640/0001-83', 'nome' => 'AFS EMPREENDIMENTOS E SERVICOS EIRELI  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '40.996.589/0001-44', 'nome' => 'SRB TOLEDO EMPREENDIMENTOS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '16.832.157/0001-13', 'nome' => 'SAMAR SOLUÇÕES AMBIENTAIS DE ARAÇATUBA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.000.000/4027-45', 'nome' => 'BANCO DO BRASIL ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.467.115/0001-00', 'nome' => 'COMPANHIA ESTADUAL DE DISTRIBUIÇÃO DE ENERGIA ELÉTRICA  CEEE']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.428.731/0122-22', 'nome' => 'PROSEGUR BRASIL S.A TRANSPOTADORA DE VALORES E SEGURANÇA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '40.432.544/0001-47', 'nome' => 'CLARO S/A ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.439.320/0001-17', 'nome' => 'GLOBAL SERVIÇOS E COMÉRCIO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.475.436/0001-49', 'nome' => 'MONTANA CONSTRUÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.899.223/0001-32', 'nome' => 'ELETROCONTROLE ENGENHARIA, COMÉRCIO E REPRESENTAÇÃO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.588.906/0001-43', 'nome' => 'CONSTRUTORA SUCESSO S.A.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.179.264/0007-66', 'nome' => 'PRESERVE SEGURANÇA DE VALORES LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.835.932/0001-08', 'nome' => 'CONPANHIA ENERGÉTICA DE PERNAMBUCO  CELPE ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.294.170/0001-38', 'nome' => 'WOLRD DIGITAL INFORMATICA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.439.655/0001-14', 'nome' => 'PEDRO REGINALDO DE ALBERNAZ FARIA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '33.050.196/0001-88', 'nome' => 'CPFL COMPANHIA PAULISTA DE FORÇA E LUZ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.367.947/0001-51', 'nome' => 'PRECISA CONSERVAÇÃO E LIMPEZA EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '29.979.036/0162-25', 'nome' => 'INSTITUTO NACIONAL DO SEGURO SOCIAL']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.996.341/0001-12', 'nome' => 'JARDINS EMPREENDIMENTOS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.856.676/0001-84', 'nome' => 'ENERGIZA ENGENHARIA LTDA  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.905.793/0001-41', 'nome' => 'JL RITT EMPREENDIMENTOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.637.812/0001-30', 'nome' => 'G. A SERVIÇOS DE APOIO ADMINISTRATIVO PARA TERCEIROS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '24.685.409/0001-57', 'nome' => 'RTCI ADMINISTRADORA DE BENS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.970.003/0001-10', 'nome' => 'METRO ENGENHARIA LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '43.776.517/0001-80', 'nome' => 'SABESP COMPANHIA DE SANEAMENTO BÁSICO DO ESTADO DE SÃO PAULO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.965.546/0001-09', 'nome' => 'CIA DE ELETRICIDADE DO AMAPA  CEA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '21.180.047/0001-54', 'nome' => 'ESTELAR LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.427.246/0001-06', 'nome' => 'FUNDO DE INVESTIMENTO IMOBIILARIO FII PRIME PORTFOLIO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.405.866/0001-57', 'nome' => 'PEDRAZUL SERVIÇOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.247.960/0001-62', 'nome' => 'REAL JG SERVIÇOS GERAIS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '24.765.629/0001-90', 'nome' => 'MENDES PARTICIPAÇÕES SOCIETÁRIAS LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.226.794/0001-55', 'nome' => 'COMPANHIA ÁGUAS DE JOINVILLE']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.865.146/0001-53', 'nome' => 'BELFORT GERENCIAMENTO DE RESÍDUOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.203.800/0001-26', 'nome' => 'TC MONITORAMENTO LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.587.568/0001-04', 'nome' => 'ROCHA DOURADO E SILVA LTDAME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.865.761/0001-06', 'nome' => 'ELITE SERVIÇOS DE SEGURANÇA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.373.051/0001-82', 'nome' => 'DOCPRINT SERVICE TECNOLOGIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.981.180/0001-16', 'nome' => 'CEMIG DISTRIBUIÇÃO S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.648.254/0001-74', 'nome' => 'BRILHAR SERVIÇOS TERCEIRIZADOS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.787.861/0001-73', 'nome' => 'ELEVADORES ALCER LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.506.307/0001-57', 'nome' => 'EMPRESA BRASILEIRA DE TECNOLOGIA E ADMINISTRAÇÃO DE CONVÊNIOS HOM LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.341.470/0001-44', 'nome' => 'BOA VISTA ENERGIA SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.443.410/0001-20', 'nome' => 'PH RECURSOS HUMANOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '94.331.832/0001-34', 'nome' => 'BRASERV ENGENHARIA & SERVIÇOS TÉCNICOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.530.036/0001-87', 'nome' => 'NATIFLORA PAISAGISMO E SERVIÇOS LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.471.879/0004-16', 'nome' => 'KASA MOTORS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.332.087/0003-66', 'nome' => 'SECURITY VIGILÂNCIA E SEGURANÇA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.234.467/0001-82', 'nome' => 'FUTURA SERVIÇOS PROFISSIONAIS ADMINISTRATIVA LTDA-EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.908.313/0001-78', 'nome' => 'BRITANICA ADMINISTRACAO & TERCEIRIZACAO EIRELI  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '35.613.306/0001-06', 'nome' => 'INCORPORADORA ULISSES PORTO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.535.897/0001-22', 'nome' => 'POTY RENT A CAR LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.798.516/0001-00', 'nome' => 'EGEL LOCADORA DE VEÍCULO DE VEÍCULOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.915.188/0001-14', 'nome' => 'M. J. LEONIDO DA SILVA RADIO TAXI  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.851.361/0001-44', 'nome' => 'DMAE DEPARTAMENTO MUNICIPAL DE ÁGUA E ESGOTO DE POÇOS DE CALDAS MG']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.062.861/0001-02', 'nome' => 'ACOMAR REFORMA E REFRIGERAÇÃO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.405.085/0001-13', 'nome' => 'DEPASA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.515.445/0001-20', 'nome' => 'CITY EMPREENDIMENTOS IMOBILIÁRIOS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.000.084/5222-91', 'nome' => 'DELMAR MACIEL CASTELO DE SOUZA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.570.442/0001-36', 'nome' => 'STAMM TRANSPORTADORA E LOGÍSTICA LTDAME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.449.286/0001-00', 'nome' => 'SUL BRASIL SEGURANÇA PRIVADA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '25.165.749/0001-10', 'nome' => 'NEO CONSULTORIA E ADMINISTRAÇÃO DE BENEFÍCIOS EIRELIEPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '63.303.267/0001-78', 'nome' => 'RADIO TAXI CAPITAL FORTALEZA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '73.822.058/0001-94', 'nome' => 'VB COMERCIO DE PECAS E SERVICOS PARA VEICULOS AUTOMOTORES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.823.840/0001-78', 'nome' => 'ELEVADORES ORION LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.291.135/0001-20', 'nome' => 'PRESTO SERVIÇOS E CONSERVAÇÃO LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.465.222/0001-01', 'nome' => 'RM TERCEIRIZAÇÃO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.940.140/0001-63', 'nome' => 'MERINVEST SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.800.421/0001-09', 'nome' => 'KWINNER SERVIÇOS DE APOIO EIRELI ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.669.451/0001-68', 'nome' => 'A.P.M DA FOSNECA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '61.074.175/0001-38', 'nome' => 'MAPFRE SEGUROS GERAIS S.A.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '14.206.326/0001-84', 'nome' => 'THERMOOK INSTALAÇÃO E MANUTENÇÃO EIRELI  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '54.222.401/0001-15', 'nome' => 'ELEVADORES VILLARTA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.332.087/0001-02', 'nome' => 'SECURITY VIGILÂNCIA E SEGURANÇA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.314.516/0001-07', 'nome' => 'CENTRO BRASILEIRO DE ENGENHARIA E SISTEMAS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.080.967/0001-44', 'nome' => 'COTTAR MANUTENÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.193.254/0001-61', 'nome' => 'ELEVADORES MASTER LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '61.600.839/0001-55', 'nome' => 'CIEE -  CENTRO DE INTEGRAÇÃO IMPRESA ESCOLA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '64.799.539/0001-35', 'nome' => 'TECNOSET PRODUTOS E SERVIÇOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.165.946/0001-10', 'nome' => 'LISERVE VIGILÂNCIA E TRANSPORTE DE VALORES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.529.815/0001-13', 'nome' => 'EMPRESA CONSTRUTORA BRILHANTE LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.441.717/0001-58', 'nome' => 'BRILHANTE ADMINISTRAÇÃO E SERVIÇOS LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '39.323.399/0001-87', 'nome' => 'UNI CONSTRUTORA E INCORPORADORA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.698.358/0001-90', 'nome' => 'JW & LOPES INTERMEDIAÇÕES IMOBILIÁRIAS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.429.693/0001-07', 'nome' => 'LISAMAR CRISTINA EMPREENDIMENTOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '61.557.039/0001-07', 'nome' => 'ITAÚ SEGUROS S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.654.086/0001-88', 'nome' => 'AMATEC AMAZÔNIA TECNOLOGIA E SISTEMAS LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.482.840/0001-38', 'nome' => 'LIDERANÇA LIMPEZA E CONSERVAÇÃO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.336.783/0001-90', 'nome' => 'CELESC DISTRIBUIÇÃO S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.056.257/0001-16', 'nome' => 'ADVANCE ELEVADORES LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '28.152.650/0001-71', 'nome' => 'ESCELSA  ESPÍRITO SANTO CENTRAIS ELÉTRICAS S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '92.780.600/0001-38', 'nome' => 'AUXILIADORA PREDIAL']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '19.086.382/0001-46', 'nome' => 'BARCELÔ EVENTOS EIRELIME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '97.548.482/0001-50', 'nome' => 'KLIMA REFRIGERAÇÃO LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.635.197/0001-35', 'nome' => 'LDC-LINHA DIRETA  COMUNICAÇÃO S/S EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '86.781.069/0001-15', 'nome' => 'ZÊNITE INFORMAÇÃO E CONSULTORIA S/A ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.689.066/0001-91', 'nome' => 'CERT LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.870.713/0001-20', 'nome' => 'SAGA COMERCIO E SERVICO TECNOLOGIA E INFORMATICA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '37.063.013/0001-10', 'nome' => 'ANDRACON SERVIÇOS GERAIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '86.960.598/0001-86', 'nome' => 'NORTH SEGURANÇA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.548.828/0001-28', 'nome' => 'DISKLIMPEZA ADMINISTRAÇAO E SERVIÇOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.039.942/0001-50', 'nome' => 'STARLIGHT SERVICE LIMPEZA DE BENS IMÓVEIS EIRELLI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.446.523/0001-10', 'nome' => 'PRESTA SERVIÇOS TÉCNICOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.091.051/0001-76', 'nome' => 'V MORETTI ASSESSORIA IMOBILIARIA LTDA-ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.447.264/0001-37', 'nome' => 'ACOFORTE SEGURANÇA E VIGILANCIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.067.719/0001-66', 'nome' => 'ITSCON TECNOLOGIA LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '21.572.243/0001-74', 'nome' => 'CESAMA COMPANHIA DE SANEAMENTO MUNICIPAL']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.162.636/0001-00', 'nome' => 'B2BR - BUSINESS TO BUSINESS INFORMÁTICA DO BRASIL LETDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '18.282.773/0001-73', 'nome' => 'IAX IMOBILIARIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.726.118/0001-27', 'nome' => 'SERVCAF LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.471.547/0001-91', 'nome' => 'CLIMATÉCNICA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '60.444.437/0001-46', 'nome' => 'LIGHT  SERVIÇOS DE ELETRICIDADE S.A.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '68.582.709/0001-86', 'nome' => 'CORPUS LINE COMÉRCIO E SERVIÇOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.251.821/0001-78', 'nome' => 'LEL SERVIÇOS GERAIS LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.758.809/0001-75', 'nome' => 'MANUTÉCNICA MANUTENÇÃO LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.199.797/0001-47', 'nome' => 'MLRJ IMOBILIARIA SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.589.220/0001-81', 'nome' => 'EFICIENCIA SERVIÇOS TERCEIRIZADOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '43.217.850/0001-59', 'nome' => 'IOB INFORMAÇÃO OBJETIVAS PUBLICAÇÕES JURÍDICAS LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '20.838.277/0001-03', 'nome' => '3R COMÉRCIO E SERVIÇOS DE MÁQUINAS LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '20.607.735/0001-95', 'nome' => 'SAAE  SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO  GOVERNADOR VALADARES']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.203.639/0001-86', 'nome' => 'TATYANA EMPREENDIMENTOS E PARTICIPAÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '18.045.377/0001-22', 'nome' => 'TULA INCORPORADORA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.918.226/0001-27', 'nome' => 'GENESIS ADMINISTRADORA DE BENS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.543.634/0001-90', 'nome' => 'TROPICAL AR COMÉRCIO E SERVIÇO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.859.652/0001-65', 'nome' => 'TAFA ENGENHARIA LTDA  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.796.152/0001-45', 'nome' => 'MINAS MOYA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '18.114.711/0001-52', 'nome' => 'RD EMPREENDIMENTOS IMOBILIARIOS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.156.351/0001-99', 'nome' => 'MUNDIAL CLEAN SERVIÇOS DE LIMPEZA LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.160.949/0001-11', 'nome' => 'VIP VIGILANCIA INTENSIVA PATRIMONIAL LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.065.033/0001-70', 'nome' => 'ELETROACRE']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.624.934/0001-46', 'nome' => 'MZ    SEGURANÇA PRIVADA LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.849.689/0001-84', 'nome' => 'BATUR - BAHIA TRANSPORTES E TURISMO - EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.283.075/0001-00', 'nome' => 'ELEVAENGE COMÉRCIO E ASSISTÊNCIA TÉCNICA EM ELEVADORES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.017.250/0001-05', 'nome' => 'VOETUR TURISMO E REPRESENTACOES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.498.257/0001-67', 'nome' => 'CENTRO OESTE ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '29.637.125/0001-09', 'nome' => 'MARCELO NOGUEIRA DOS SANTOS, DRY JET DELIVERY']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.872.024/0001-42', 'nome' => 'CALDAS SERVICE LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '14.533.285/0001-30', 'nome' => 'CONAMA CONSTRUÇÕES AMAPAENSE EIRELI ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.062.071/0001-06', 'nome' => 'SEGURANÇA COMERCIAL DO PIAUÍ LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.281.106/0001-03', 'nome' => 'COPASA COMPANHIA DE SANEAMENTO DE MINAS GERAIS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '25.769.548/0001-21', 'nome' => 'DMAE DEPARTAMENTO MUNICIPAL DE ÁGUA E ESGOTO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.266.468/0001-58', 'nome' => 'URBS - EMPREENDIMENTOS IMOBILIÁRIOS E CONSULTORIA LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.354.359/0001-92', 'nome' => 'INCOESTE INSTALAÇÕES E CONSTRUÇÕES LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.609.260/0001-12', 'nome' => 'NOVA PROVA PRESTAÇÃO DE SERVIÇOS LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.992.128/0001-77', 'nome' => 'BC EMPREENDIMENTOS E PARTICIPAÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '33.438.433/0001-82', 'nome' => 'FRANCAR AULTO PEÇAS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.073.929/0001-00', 'nome' => 'MILENIUM ADMINISTRADORA DE BENS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '14.320.818/0001-04', 'nome' => 'NTB TOWER EMPREEDIMENTOS IMOBILIÁRIOS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.976.311/0001-04', 'nome' => 'CAESA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.325.594/0001-64', 'nome' => 'TECSEG TECNOLOGIA EM SEGURANÇA PRIVADA EIRELI EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '32.500.613/0001-84', 'nome' => 'CAIXA BENEFICENTE DA COMPANHIA DE SIDERURGIA NACIONAL - ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.360.551/0001-54', 'nome' => 'INTERSEPT LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.137.011/0001-92', 'nome' => 'NEGÓCIOS, SOLUÇÕES E CONSULTORIA IMOBILIÁRIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.026.942/0001-16', 'nome' => 'ELEVADORES VERSÁTIL LTDA  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.000.626/9420-04', 'nome' => 'CERIZE DA SILVA GUTIERREZ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.116.723/0001-86', 'nome' => 'VIGILANCIA URBANA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '90.347.840/0011-90', 'nome' => 'THYSSENKRUPP ELEVADORES S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '62.490.099/0001-04', 'nome' => 'COMERCIAL CONSTRUTORA E INCOPORORADORA ITARARÉ LTD']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.777.162/0001-57', 'nome' => 'BASIS TECNOLOGIA DA INFORMAÇÃO S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.815.892/0001-03', 'nome' => 'ASA  AGÊNCIA DE SERVIÇOS DO ACREEPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.372.929/0001-19', 'nome' => 'RICCI SERVICES EIRELLI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.543.032/0001-04', 'nome' => 'CELG DISTRIBUIÇÃO S.A.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.041.666/0001-62', 'nome' => 'MOURA COMÉRCIO DE DERIVADOS DE PETRÓLEO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '26.990.812/0001-15', 'nome' => 'TECNISYS INFORMÁTICA E ASSESSORIA EMPRESARIAL LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.367.810/0001-60', 'nome' => 'CENTRO SERRA EMPREENDIMENTOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '71.208.516/0001-74', 'nome' => 'ALGAR TELECOM S.A.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.933.418/0001-78', 'nome' => 'SEGPLUS - SISTEMA DE SEGURANÇA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.018.845/0001-77', 'nome' => 'JM TORRES JORNAIS E REVISTAS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.914.650/0001-66', 'nome' => 'CENTRAIS ELÉTRICAS DE RONDÔNIA S.A ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.926.280/0001-17', 'nome' => 'ALL TECH ELEVADORES SERVIÇOS LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.536.754/0003-95', 'nome' => 'J. CAMARA & IRMÃOS SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.788.943/0001-47', 'nome' => 'UNIKA TERCEIRIZAÇÃO E SERVICOS EIRELI  EPP.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.840.079/0001-10', 'nome' => 'HANANKA IMOBILIÁRIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '32.469.645/0001-64', 'nome' => 'CETEST ES  - MANUTENÇÃO E UTILIDADES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '18.791.267/0001-00', 'nome' => 'ACF IMOBILIARIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '27.149.997/0001-00', 'nome' => 'ECOSENSE AMBIENTAL LTDA  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.295.223/0001-40', 'nome' => 'LINCE MOTORS S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.949.783/0001-70', 'nome' => 'SANTA FÉ CONSTRUÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.150.504/0001-65', 'nome' => 'LDS SERVIÇOS D ELIMPEZA EIRELI EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.238.297/0001-89', 'nome' => '3 CORP TECHNOLOGY SA INFRAESTRUTURA DE TELECOM']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.383.621/0001-18', 'nome' => 'SIE SERVIÇOS, CURSOS E COMÉRCIO DE PEÇAS INDUSTRIAIS LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.949.483/0001-75', 'nome' => 'A ABBA SERVIÇOS GERAIS LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '43.714.674/0001-60', 'nome' => 'CONSTRUTORA E INCORPORADORA EXATA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.783.615/0001-80', 'nome' => 'SMIDI PARTICIPAÇÕES IMOBILIÁRIAS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.471.879/0001-73', 'nome' => 'KASA MOTORS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.038.465/0001-67', 'nome' => 'ARMAZÉM DIGITAL COMUNICAÇÃO E INFORMAÇÃO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '24.118.443/0001-40', 'nome' => 'TOP CAR LAVAGEM ECOLÓGICA DE VEÍCULOS LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.715.056/0001-58', 'nome' => 'SHIGEAKI MARACAJÁ RAMOS ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '30.656.873/0001-18', 'nome' => 'LH NEGÓCIOS IMOBILIÁRIOS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.272.098/0001-90', 'nome' => 'FORT SELECT LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.650.283/0001-91', 'nome' => 'DFTI COMERCIO E SERVIÇOS DE INFORMÁTICA LTDA  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.149.706/0001-10', 'nome' => 'ALAMO SEGURANÇA ELETRONICA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.952.601/0001-55', 'nome' => 'PREMIUM MÃO DE OBRA ESPECIALIZADA, ENGENHARIA E LOCAÇÕES EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.718.633/0001-90', 'nome' => 'AMAZON SECURITY']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.923.940/0001-79', 'nome' => 'BRAZILIAN FINANCIAL CENTER']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.395.624/0001-79', 'nome' => 'VERMA ENGENHARIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '43.035.146/0051-44', 'nome' => 'PROTEGE SA PROTEÇÃO E TRANSPORTE DE VALORES  ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '38.044.723/0001-65', 'nome' => 'MULTI CONSTRUTORA E INCORPORADORA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '49.101.280/0001-13', 'nome' => 'SERVIÇO AUTÔNOMO DE ÁGUA E ESGOTO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '14.010.744/0001-00', 'nome' => 'A3 GESTÃO DE PESSOAS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '97.456.065/0001-88', 'nome' => 'MINAS TURISMO E SERVIÇOS LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.150.147/0001-00', 'nome' => 'GP7 LOGÍSTICA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.193.434/0001-79', 'nome' => 'CONDOMINIO COMERCIAL TIFFANY OFFICE PLAZA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.426.041/0001-47', 'nome' => 'ALSERVICE SERVIÇOS ESPECIALIZADOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.696.939/0001-96', 'nome' => 'SELME SERVIÇOS EMPRESARIAIS LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '97.371.470/0001-01', 'nome' => 'QUIMITEC QUÍMICA INDUSTRIAL LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.311.279/0001-40', 'nome' => 'EUNICE MARIA GONÇALVES DE OLIVEIRA  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.043.066/0001-94', 'nome' => 'M. DO ESPÍRITO SANTO LIMA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.302.100/0001-06', 'nome' => 'BANDEIRANTE ENERGIA SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '68.970.680/0001-00', 'nome' => 'ERODATA CONSULTORIA E SERVIÇOS LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '59.996.884/0003-90', 'nome' => 'CONDOMINIO DO EDIFICIO GARDEN TRADE CENTER']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.097.626/0001-68', 'nome' => 'BRASAL COMBUSTIVEIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.937.230/0001-06', 'nome' => 'DMB SEGURANÇA PRIVADA LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.324.303/0001-83', 'nome' => 'PCN  IMOVEIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '54.038.583/0001-79', 'nome' => 'GB BARIRI SERVIÇOS GERAIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '33.050.071/0001-58', 'nome' => 'AMPLA ENERGIA E SERVIÇOS S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.643.692/0001-96', 'nome' => 'ASSOCIAÇÃO DE PAIS E AMIGOS DOS EXCEPCIONAIS DO DISTRITO FEDERAL']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.320.095/0001-07', 'nome' => 'UNIQUE RENT A CAR LOCADORA DE VEÍCULOS LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '26.695.318/0001-28', 'nome' => 'CONDOMINIO DO PARQUE']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.375.721/0001-30', 'nome' => 'MGI EMPREENDIMENTOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.409.620/0001-53', 'nome' => 'STAR SERVIÇOS ESPECIALIZADOS DE MÃO DE OBRA EIRELI  ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.581.314/0001-98', 'nome' => 'ENAI ENGENHARIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.753.848/0001-42', 'nome' => 'EPIFANIO MONTEIRO CIA LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '28.133.715/0001-31', 'nome' => 'CENTRO COMERCIAL AQUARIUS CENTER']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.692.962/0001-51', 'nome' => 'KODAK ALARIS BRASIL COMÉRCIO DE MATERIAL FOTOGRÁFICO E SERVIÇOS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '14.339.328/0001-41', 'nome' => 'ATRATIVA SERVICE LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.934.677/0001-83', 'nome' => 'URBI EMPREENDIMENTOS IMOBILIÁRIOS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '56.022.858/0001-01', 'nome' => 'DEPARTAMENTO DE ÁGUA E ESGOTOS DE RIBEIRÃO PRETO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '28.835.080/0001-14', 'nome' => 'GALERIA LO BIANCO LOCAÇÃO DE IMOVEIS LTDA  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.514.896/0001-15', 'nome' => 'THOMAS GREG & SONS GRÁFICA E SERVIÇOS, INDUSTRIA E COMÉRCIO LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.739.782/0001-27', 'nome' => 'FORÇA TÁTICA VIGILÂNCIA E SEGURANÇA EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '71.480.560/0001-39', 'nome' => 'SERVIÇO AUTÔNOMO DE AGUA E ESGOTO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.713.403/0001-90', 'nome' => 'RECHE GALDEANO & CIA LTDA - EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.558.255/0001-25', 'nome' => 'INOVADORA 2A SERVIÇOS SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '29.739.737/0011-84', 'nome' => 'ELEVADORES OTIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.422.570/0001-23', 'nome' => 'JBC  NEGÓCIOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.109.093/0001-39', 'nome' => 'OBJETIVA ADMINISTRAÇÃO DE SERVIÇOS EIRELI ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.709.818/0001-27', 'nome' => 'R.A. EMPREENDIMENTOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '31.132.707/0001-85', 'nome' => 'PETRO GELLI IMOBILIÁRIA LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '25.433.004/0001-94', 'nome' => 'CODAU CENTRO OPERACIONAL DE DESENVOLVIMENTO E SANEAMENTO DE UBERABA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '42.821.603/0001-02', 'nome' => 'SIOTECH AR CONDICIONADO LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.786.457/0001-90', 'nome' => 'POSTO Z Z NOSSA SENHORA  MEDALHA MILAGROSA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '82.891.805/0001-37', 'nome' => 'PATRIMONIAL SEGURANÇA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.172.213/0001-51', 'nome' => 'CPFL COMPANHIA PIRATININGA DE FORÇA E LUZ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '72.602.303/0001-95', 'nome' => 'PURÍSSIMA ÁGUA MINERAL']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.881.488/0001-39', 'nome' => 'MCB CURSOS E TREINAMENTOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '17.157.967/0001-84', 'nome' => 'MIPRISA INVESTIMENTOS IMOBILIÁRIOS E PARTICIPAÇÕES LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.398.928/0001-90', 'nome' => 'MONARCA PARTICIPAÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.169.044/0001-75', 'nome' => 'SISTEMAX COMERCIO DE PRODUTOS ELETRONICOS EIRELLI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '18.083.458/0001-17', 'nome' => 'ARCOM COMÉRCIO E SERVIÇOS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.527.773/0001-47', 'nome' => 'CORE SERVIÇOS E INFORMÁTICA LTDA  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.317.343/0001-84', 'nome' => 'FAMA SERVICE ADM SERVIÇOS GERAIS EIRELI ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.237.191/0001-51', 'nome' => 'SECRETARIA DE ESTADO DE CASA CIVIL E REL INSTITUCIONAIS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.911.840/0001-92', 'nome' => 'NEXUS VIGILÂNCIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '29.572.104/0001-52', 'nome' => 'JUNPET EMPREENDIMENTOS E PARTICIPAÇÕES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.282.377/0001-20', 'nome' => 'CAIUÁ DISTRIBUIÇÃO DE ENERGIA SA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '61.695.227/0001-93', 'nome' => 'AES ELETROPAULO METROPOLITANA ELETRICIDADE DE SÃO PAULO SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.602.789/0001-01', 'nome' => 'DATEN TECNOLOGIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '83.953.331/0001-73', 'nome' => 'ONDREPSB LIMPEZA E SERVIÇOS ESPECIAIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.791.353/0001-24', 'nome' => 'AJB DE AVILAR & CIA LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.056.546/0001-31', 'nome' => 'GR3 SERVLCOS E CONSTRUCOES LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '31.864.606/0001-07', 'nome' => 'TECNENGE TECNOLOGIA DE ENGENHARIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.725.585/0001-60', 'nome' => 'INDEX MÍDIAS INTERATIVAS LTDA ME ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '32.578.387/0003-16', 'nome' => 'UNITECH RIO COMÉRCIO E SERVIÇOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.342.488/0001-47', 'nome' => 'META SERVIÇOS E MATERIAIS MG EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.831.073/0001-86', 'nome' => 'ZETEC MANUTENÇÃO DE VEÍCULOS E MOTORES LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.697.640/0001-44', 'nome' => 'SAGE BRASÍLIA CONSULTORIA E PROJETOS EM ENERGIA E MEIO AMBIENTE EIRELI  ME ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '16.830.096/0001-55', 'nome' => 'FORTE LIMP ADMINISTRAÇÃO E SERVIÇOS EIRELI ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.219.617/0001-04', 'nome' => 'CITY SERVICE SERVIÇOS TERCEIRIZADOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.732.146/0001-85', 'nome' => 'SR TERCEIRIZAÇÕES EIRELI ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '03.056.608/0001-26', 'nome' => 'J&M COMÉRCIO E SERVIÇOS DE TELECOMUNICAÇÕES E INFORMÁTICA LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.691.905/0001-55', 'nome' => 'COOPERATIVA MISTA DE CONSUMO E PRESTAÇÃO DE SERVIÇO EM TRANSPORTE RODOVIÁRIO  COOPERTRAN']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.812.686/0001-15', 'nome' => 'ORANGE SYSTEM MONITORAMENTO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '65.295.172/0001-85', 'nome' => 'MÉTODO TELECOMUNICAÇÕES']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '81.243.735/0019-77', 'nome' => 'POSITIVO TECNOLOGIA S.A.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '50.853.555/0001-54', 'nome' => 'SEMAE SERVIÇO MUNICIPAL DE AGUA E ESGOTO DE PIRACICABA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.413.826/0001-50', 'nome' => 'EMPRESA ENERGÉTICA DE MATO GROSSO DO SUL S A ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '19.340.324/0001-05', 'nome' => 'LEMONDE NEGÓCIOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.319.323/0001-91', 'nome' => 'PANTANAL VEÍCULOS LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.146.946/0001-02', 'nome' => 'PP LIMPEZA E CONSERVAÇÃO LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.216.620/0001-37', 'nome' => 'BRS SUPRIMENTOS CORPORATIVOS S.A.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '24.030.023/0001-07', 'nome' => 'TRECH SOLUÇÕES DIGITAIS EIRELI  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.091.569/0001-96', 'nome' => 'ODONTOTEC ASSIS COMÉRCIO E SERVIÇOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.107.666/0001-20', 'nome' => 'AVANTE BRASIL  INFORMÁTICA E TREINAMENTOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '22.415.029/0001-77', 'nome' => 'ESOFEN ENERGY  ENGENHARIA DE SUSTENTABILIDADE LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.979.037/0001-90', 'nome' => 'INOVA SERVIÇOS DE MÃO DE OBRA EIRELI EPP ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '05.757.597/0002-18', 'nome' => 'TECHBIZ FORENSE DIGITAL S.A.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.718.634/0001-26', 'nome' => 'CAPITAL BRASILEIRO DE EMPREENDIMENTOS IMOBILIÁRIOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.993.386/0001-33', 'nome' => 'FUNDO DE INVEST IMOBILIÁRIO FII CASTELO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.200.174/0001-06', 'nome' => 'LOCATIVA EMPREENDIMENTOS IMOBILIÁRIOS LTA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '37.077.716/0001-05', 'nome' => 'CITY SERVICE SEGURANÇA LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.758.292/0001-42', 'nome' => 'LÍDER FORTE SERVIÇOS EMPRESARIAIS LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.604.149/0001-54', 'nome' => 'LÍDER VIGILÂNCIA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.901.037/0001-00', 'nome' => 'EDR SOLUÇÕES EMPRESARIAIS LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '90.347.840/0016-02', 'nome' => 'THYSSENKRUP ELEVADORES SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '19.594.684/0001-25', 'nome' => 'DIPLUS SISTEMAS E SERVIÇOS DE INFORMÁTICA EIRELLI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.816.182/0001-07', 'nome' => 'CASA NOVA LOCADORA LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '72.638.349/0001-64', 'nome' => 'LANCHONETE DO TIO LTDA  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '37.071.313/0001-40', 'nome' => 'EMIBM ENGENHARIA E COMÉRCIO LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '69.207.850/0001-61', 'nome' => 'RCA PRODUTOS E SERVIÇOS LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '06.154.596/0001-60', 'nome' => 'DMJL PARTICIPACÕES LTDA.']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '84.552.892/0001-23', 'nome' => 'RECUPERAR RECUPERAÇÃO E MANUTENÇÃO DE AR CONDICIONADO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.949.785/0001-55', 'nome' => 'NORTE LOCADORA DE VEÍCULOS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.369.330/0001-75', 'nome' => 'ABC TRANSPORTES E TERCERIZAÇÃO DE MAO DE OBRA LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.697.422/0001-00', 'nome' => 'GED PRESTADORA DE SERVIÇOS GERAIS LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '07.634.564/0001-25', 'nome' => 'ANKARA SERVIÇOS TERCEIRIZAVEIS EIRELI  ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '24.929.614/0001-10', 'nome' => 'MIRANDA TURISMO E REPRESENTAÇÕES']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '10.658.360/0001-39', 'nome' => 'ATENAS ELEVADORES LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '82.508.433/0001-17', 'nome' => 'COMPANHIA CATARINENSE DE AGUAS E SANEAMENTO  CASAN']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.661.695/0001-15', 'nome' => 'SANTOS EMPREENDIMENTOS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.388.132/0001-00', 'nome' => 'ELEVADORES E CONSERVADORA ALIANÇA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '13.080.938/0001-00', 'nome' => 'PPX INFO COMERCIO DE EQUIPAMENTOS']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.300.567/0001-50', 'nome' => 'R. C. V. R. DE OLIVEIRA LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '01.723.789/0001-71', 'nome' => 'CONSERVADORA CAMPOS E SERVIÇOS GERAIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.561.137/0001-90', 'nome' => 'R M SERVIÇOS EMPRESARIAIS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.063.100/0001-46', 'nome' => 'JMK PARTICIPAÇÕES SOCIETÁRIAS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '15.718.607/0001-89', 'nome' => 'HK SERVIÇOS TERCEIRIZADOS LTDA EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '37.057.387/0001-22', 'nome' => 'HEPTA TECNOLOGIA E INFORMÁTICA LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '14.487.384/0001-23', 'nome' => 'CAPIM DOURADO RENT A CAR LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '42.040.279/0001-87', 'nome' => 'CONVIC CONSERVACAO E SERVICOS GERAIS EIRELI  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '12.372.650/0001-47', 'nome' => 'CANERE IMÓVEIS LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.489.015/0001-65', 'nome' => 'CONSERP MANUTENÇÃO DE ELEVADORES LTDA  EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '46.139.952/0001-91', 'nome' => 'DEPARTAMENTO DE AGUA E ESGOTO DE BAURU']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '02.016.440/0001-62', 'nome' => 'RGE SUL DISTRIBUIDORA DE ENERGIA S.A']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.970.088/0001-25', 'nome' => 'PLANSERVICE TERCEIRIZAÇÃO DE SERVIÇOS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.368.898/0001-06', 'nome' => 'COPEL DISTRIBUIÇÃO SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.134.888/0001-20', 'nome' => 'IMPERIAL RONDÔNIA FORNEC. E GESTÃO RECURSOS HUMANOS PARA TERCEIROS LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '11.399.787/0001-22', 'nome' => 'VENEZA SERVICOS ADMINISTRATIVOS EIRELI']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '29.000.841/0001-80', 'nome' => 'TECNISAN TÉCNICA DE SERVIÇOS E COMÉRCIO LTDA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '09.252.432/0001-64', 'nome' => 'VCS ELÉTRICA SERVIÇOS DE CHAVEIROS E CONFECÇÃO DE CARIMBOS LTDA ME']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '04.236.076/0001-71', 'nome' => 'INSTITUTO DE DESENVOLVIMENTO EDUCACIONAL, CULTURAL E ASSISTENCIAL NACIONAL,']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '00.681.882/0001-06', 'nome' => 'ENTHERME ENGENHARIA DE SISTEMAS TERMOMECÂNICOS LTDA ']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '19.877.285/0003-33', 'nome' => 'LANLINK SOLUÇÕES E COMERCIALIZAÇÃO EM INFORMÁTICA SA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'JURIDICA', 'cpf_cnpj_idgener' => '08.823.749/0001-40', 'nome' => 'R. PINHEIRO GRIMM TRANSPORTES EPP']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'UG', 'cpf_cnpj_idgener' => '115406', 'nome' => 'EMPRESA BRASIL DE COMUNICAÇÃO']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'UG', 'cpf_cnpj_idgener' => '803010', 'nome' => 'SERPRO REGIONAL BRASILIA']);
        DB::table('fornecedores')->insert(['tipo_fornecedor' => 'UG', 'cpf_cnpj_idgener' => '806030', 'nome' => 'SERPRO REGIONAL BRASILIA SEDE']);

    }
}
