<?php

use Illuminate\Database\Seeder;

// composer require laracasts/testdummy
use Laracasts\TestDummy\Factory as TestDummy;

class NaturezadespesaSeeder extends Seeder
{
    public function run()
    {
        DB::table('naturezadespesa')->insert(['codigo' => '300000', 'descricao' => 'DESPESAS CORRENTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '310000', 'descricao' => 'PESSOAL E ENCARGOS SOCIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '313000', 'descricao' => 'TRANSF. A ESTADOS E AO DISTRITO FEDERAL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '313041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '313099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317000', 'descricao' => 'TRANSF. A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317100', 'descricao' => 'TRANSF.CONSOR.PUB.MEDIANTE CONTRATO DE RATEIO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317111', 'descricao' => 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317116', 'descricao' => 'OUTRAS DESPESAS VARIAVEIS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317170', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317196', 'descricao' => 'RESSARCIMENTO DE DESP.DE PESSOAL REQUISITADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317300', 'descricao' => 'TRANSFERENCIA A CONSORCIOS PULBICOS LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317370', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317400', 'descricao' => 'TRANSFERENCIA A CONSORCIOS PULBICOS LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '317470', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '318000', 'descricao' => 'TRANSFEENCIAS AO EXTERIOR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '318004', 'descricao' => 'CONTRATACAO POR TEMPO DETERMINADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '318034', 'descricao' => 'OUTRAS DESP. PESSOAL CONTRATOSDE TERCEIRIZ.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '318099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319000', 'descricao' => 'APLICACOES DIRETAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319001', 'descricao' => 'APOSENT.RPPS, RESER.REMUNER. E REFOR.MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319003', 'descricao' => 'PENSOES DO RPPS E DO MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319004', 'descricao' => 'CONTRATACAO P/TEMPO DETERMINADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319005', 'descricao' => 'OUTROS BENEF.PREV. DO SERVIDOR OU DO MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319007', 'descricao' => 'CONTRIB. A ENTIDADES FECHADAS DE PREVIDENCIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319008', 'descricao' => 'OUTROS BENEF.ASSIST. DO SERVIDOR E DO MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319009', 'descricao' => 'SALARIO-FAMILIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319011', 'descricao' => 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319012', 'descricao' => 'VENCIMENTOS E VANTAGENS FIXAS - PES. MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319013', 'descricao' => 'OBRIGACOES PATRONAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319016', 'descricao' => 'OUTRAS DESPESAS VARIAVEIS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319017', 'descricao' => 'OUTRAS DESPESAS VARIAVEIS - PESSOAL MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319034', 'descricao' => 'OUTRAS DESP.PESSOAL DEC. CONTRATOS TERCEIRIZ.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319059', 'descricao' => 'PENSOES ESPECIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319067', 'descricao' => 'DEPOSITOS COMPULSORIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319091', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319094', 'descricao' => 'INDENIZACOES E RESTITUICOES TRABALHISTAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319096', 'descricao' => 'RESSARCIMENTO DE DESP. DE PESSOAL REQUISITADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319100', 'descricao' => 'APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319104', 'descricao' => 'CONTRATACAO POR TEMPO DETERMINADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319113', 'descricao' => 'OBRIGACOES PATRONAIS - OP.INTRA-ORCAMENTARIAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319191', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319192', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319194', 'descricao' => 'INDENIZACOES TRABALHISTAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319196', 'descricao' => 'RESSARCIMENTO DE DESP. DE PESSOAL REQUISITADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319500', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319504', 'descricao' => 'CONTRATACAO POR TEMPO DETERMINADO LC 141/2012', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319507', 'descricao' => 'CONTRIBUICAO A ENTIDADE FECHADA PREVIDENCIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319511', 'descricao' => 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319513', 'descricao' => 'OBRIGACOES PATRONAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319516', 'descricao' => 'OUTRAS DESPESAS VARIAVEIS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319567', 'descricao' => 'DEPOSITOS COMPULSORIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319591', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319594', 'descricao' => 'INDENIZACOES E RESTITUICOES TRABALHISTAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319596', 'descricao' => 'RESSARCIMENTO DESPESAS DE PESSOAL REQUISITADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319600', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319604', 'descricao' => 'CONTRATACAO POR TEMPO DETERMINADO LC 141/2012', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319607', 'descricao' => 'CONTRIBUICAO A ENTIDADE FECHADA PREVIDENCIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319611', 'descricao' => 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319613', 'descricao' => 'OBRIGACOES PATRONAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319616', 'descricao' => 'OUTRAS DESPESAS VARIAVEIS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319667', 'descricao' => 'DEPOSITOS COMPULSORIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319691', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319694', 'descricao' => 'INDENIZACOES E RESTITUICOES TRABALHISTAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '319696', 'descricao' => 'RESSARCIMENTO DESPESAS DE PESSOAL REQUISITADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '320000', 'descricao' => 'JUROS E ENCARGOS DA DIVIDA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '327000', 'descricao' => 'TRANSF. A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '327100', 'descricao' => 'TRANSF.CONSORC.PUB.MEDIANTE CONTRATO RATEIO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '327170', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '327300', 'descricao' => 'TRANSFERENCIA A CONSORCIOS PULBICOS LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '327370', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '327400', 'descricao' => 'TRANSFERENCIA A CONSORCIOS PULBICOS LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '327470', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329000', 'descricao' => 'APLICACOES DIRETAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329021', 'descricao' => 'JUROS SOBRE A DIVIDA POR CONTRATO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329022', 'descricao' => 'OUTROS ENCARGOS SOBRE A DIVIDA POR CONTRATO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329023', 'descricao' => 'JUROS,DESAGIOS E DESCONTOS DA DIV. MOBILIARIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329024', 'descricao' => 'OUTROS ENCARGOS SOBRE A DIVIDA MOBILIARIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329025', 'descricao' => 'ENC.SOBRE OPER.DE CRED.POR ANTEC. DA RECEITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329026', 'descricao' => 'OBRIGACOES DECORRENTES DE POLITICA MONETARIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329091', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329093', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329123', 'descricao' => 'JUROS,DESAGIOS E DESCONTOS DA DIV. MOBILIARIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329500', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329521', 'descricao' => 'JUROS SOBRE A DIVIDA POR CONTRATO - LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329522', 'descricao' => 'OUTROS ENCARGOS SOBRE A DIVIDA POR CONTRATO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES - LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329600', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329621', 'descricao' => 'JUROS SOBRE A DIVIDA POR CONTRATO - LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329622', 'descricao' => 'OUTROS ENCARGOS SOBRE A DIVIDA POR CONTRATO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES - LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329900', 'descricao' => 'A DEFINIR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '329999', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '330000', 'descricao' => 'OUTRAS DESPESAS CORRENTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332001', 'descricao' => 'APOSENTADORIAS E REFORMAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332003', 'descricao' => 'PENSOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332014', 'descricao' => 'DIARIAS - CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332030', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332035', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332036', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332039', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '332200', 'descricao' => 'EXECUCAO ORCAMENTARIA DELEGADA AA UNIAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333000', 'descricao' => 'TRANSFER.  A ESTADOS E AO DISTRITO FEDERAL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333014', 'descricao' => 'PAGAMENTO DE DIARIAS-CIVIL NO PAIS E EXTERIOR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333015', 'descricao' => 'PAGTO DE DIARIAS-MILITAR NO PAIS E EXTERIOR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333018', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333020', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333030', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333033', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333035', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333036', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333039', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333043', 'descricao' => 'SUBVENCOES SOCIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333047', 'descricao' => 'OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333081', 'descricao' => 'DISTRIBUICAO DE RECEITAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333093', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333100', 'descricao' => 'TRANSFER. A ESTADOS E AO DF - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333141', 'descricao' => 'CONTRIBUICOES - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333192', 'descricao' => 'DESPESAS DE EXERC. ANTERIORES FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333200', 'descricao' => 'EXECUCAO ORCAMENTARIA DELEGADA AOS ESTADOS/DF', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333214', 'descricao' => 'DIARIAS - CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333218', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333220', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333230', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333232', 'descricao' => 'MATERIAL, BEM OU SERVICO P/ DISTRIB. GRATUITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333233', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333235', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333236', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333239', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333292', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333293', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333500', 'descricao' => 'TRANSFERENCIAS FUNDO A FUNDO ART.24 LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333541', 'descricao' => 'CONTRIBUICOES (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333600', 'descricao' => 'TRANSFERENCIAS FUNDO A FUNDO ART.25 LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333641', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '333692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334000', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334014', 'descricao' => 'DIARIAS - CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334018', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334030', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334033', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334035', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334036', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS ± PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334039', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334043', 'descricao' => 'SUBVENCOES SOCIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334047', 'descricao' => 'OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334081', 'descricao' => 'DISTRIBUICAO DE RECEITAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334091', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334093', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334100', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334141', 'descricao' => 'CONTRIBUICOES - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334192', 'descricao' => 'DESPESAS DE EXERC. ANTERIORES FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334200', 'descricao' => 'EXECUCAO ORCAMENTARIA DELEGADA A MUNICIPIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334214', 'descricao' => 'DIARIAS - CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334230', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334232', 'descricao' => 'MATERIAL, BEM OU SERVICO P/ DISTRIB. GRATUITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334233', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334235', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334236', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334239', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334292', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334293', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334500', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS ART.24 LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334541', 'descricao' => 'CONTRIBUICOES (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334591', 'descricao' => 'SENTENCAS JUDICIAIS (ACOES/SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334600', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS ART.25 LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334641', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334691', 'descricao' => 'SENTENCAS JUDICIAIS (ACOES/SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '334692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335000', 'descricao' => 'TRANSF. A INST. PRIVADAS SEM FINS LUCRATIVOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335014', 'descricao' => 'DIARIAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335018', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335020', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335030', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335031', 'descricao' => 'PREMIACOES CULT.ART.CIENT.DESPORTIVAS E OUTRA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335033', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335035', 'descricao' => 'SERVICO DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335036', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335039', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335043', 'descricao' => 'SUBVENCOES SOCIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335047', 'descricao' => 'OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '335099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '336000', 'descricao' => 'TRANSFER.A INST. PRIVADAS COM FINS LUCRATIVOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '336041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '336045', 'descricao' => 'SUBVENCOES ECONOMICAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '336092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '336099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337000', 'descricao' => 'TRANSF. A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337100', 'descricao' => 'TRANSF.CONSORC.PUB.MEDIANTE CONTRATO RATEIO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337114', 'descricao' => 'DIARIAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337130', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337133', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337134', 'descricao' => 'OUTRAS DESPESAS DE PESSOAL - TERCEIRIZACAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337136', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337139', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337141', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337146', 'descricao' => 'INDENIZACAO AUXILIO-ALIMENTACAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337170', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337193', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337200', 'descricao' => 'EXECUCAO ORCAM.DELEGADA A CONSORCIOS PUBLICOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337239', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS PJ - OP.INT.ORC.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337300', 'descricao' => 'TRANSFERENCIA A CONSORCIOS PULBICOS LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337370', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337400', 'descricao' => 'TRANSFERENCIA A CONSORCIOS PULBICOS LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337470', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337500', 'descricao' => 'TRANSF.A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337541', 'descricao' => 'CONTRIBUICOES (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337600', 'descricao' => 'TRANSF.A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '337641', 'descricao' => 'CONTRIBUICOES (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338000', 'descricao' => 'TRANSFERENCIAS AO EXTERIOR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338004', 'descricao' => 'CONTRATACAO POR TEMPO DETERMINADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338014', 'descricao' => 'DIARIAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338030', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338033', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338034', 'descricao' => 'OUTRAS DESP.PESSOAL DEC. CONTRATOS TERCEIRIZ.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338035', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338036', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS ± PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338037', 'descricao' => 'LOCACAO DE MAO-DE-OBRA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338039', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '338099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339000', 'descricao' => 'APLICACOES DIRETAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339001', 'descricao' => 'APOSENT.RPPS, RESER. REMUNER. E REFOR.MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339003', 'descricao' => 'PENSOES, EXCLUSIVE DO RGPS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339004', 'descricao' => 'CONTRATACAO POR TEMPO DETERMINADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339005', 'descricao' => 'OUTROS BENEFICIOS PREVIDENCIARIOS DO RPPS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339006', 'descricao' => 'BENEFICIO MENSAL AO DEFICIENTE E AO IDOSO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339008', 'descricao' => 'OUTROS BENEF.ASSIST. DO SERVIDOR E DO MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339009', 'descricao' => 'SALARIO-FAMILIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339010', 'descricao' => 'SEGURO DESEMPREGO E ABONO SALARIAL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339014', 'descricao' => 'DIARIAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339015', 'descricao' => 'DIARIAS - PESSOAL MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339018', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339019', 'descricao' => 'AUXILIO-FARDAMENTO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339020', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339026', 'descricao' => 'OBRIGACOES DECORRENTES DE POLITICA MONETARIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339027', 'descricao' => 'ENC.P/ HONRA DE AVAIS, GARANT.,SEGUROS E SIM.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339028', 'descricao' => 'REMUNERACAO DE COTAS DE FUNDOS AUTARQUICOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339030', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339031', 'descricao' => 'PREMIACOES CULT., ART., CIENT., DESP. E OUTR.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339032', 'descricao' => 'MATERIAL, BEM OU SERVICO P/ DISTRIB. GRATUITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339033', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339034', 'descricao' => 'OUTRAS DESP.PESSOAL DEC. CONTRATOS TERCEIRIZ.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339035', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339036', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339037', 'descricao' => 'LOCACAO DE MAO-DE-OBRA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339038', 'descricao' => 'ARRENDAMENTO MERCANTIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339039', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339040', 'descricao' => 'SERVICOS DE TECNOLOGIA DA INFORMACAO E COMUNICACAO - PJ', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339045', 'descricao' => 'SUBVENCOES ECONOMICAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339046', 'descricao' => 'AUXILIO-ALIMENTACAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339047', 'descricao' => 'OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339048', 'descricao' => 'OUTROS AUXILIOS FINANCEIROS A PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339049', 'descricao' => 'AUXILIO-TRANSPORTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339053', 'descricao' => 'APOSENTADORIAS DO RGPS - AREA RURAL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339054', 'descricao' => 'APOSENTADORIAS DO RGPS - AREA URBANA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339055', 'descricao' => 'PENSOES DO RGPS - AREA RURAL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339056', 'descricao' => 'PENSOES DO RGPS - AREA URBANA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339057', 'descricao' => 'OUTROS BENEFICIOS DO RGPS - AREA RURAL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339058', 'descricao' => 'OUTROS BENEFICIOS DO RGPS - AREA URBANA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339059', 'descricao' => 'PENSOES ESPECIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339067', 'descricao' => 'DEPOSITOS COMPULSORIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339081', 'descricao' => 'DISTRIBUICAO CONSTITUCIONAL OU LEGAL DE RECEITAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339091', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339093', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339095', 'descricao' => 'INDENIZACAO PELA EXECUCAO TRABALHOS DE CAMPO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339096', 'descricao' => 'RESSARC. DE DESPESAS DE PESSOAL REQUISITADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339098', 'descricao' => 'COMPENSACOES AO RGPS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339100', 'descricao' => 'APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339104', 'descricao' => 'CONTRATATACAO POR TEMPO DETERMINADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339118', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339128', 'descricao' => 'REM.DE COTAS FUNDOS AUTARQUICOS-OP.INTRA-ORC.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339129', 'descricao' => 'DIVIDENDOS - EMPRESAS ESTATAIS DEPENDENTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339130', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339131', 'descricao' => 'PREMIACOES CULT., ART., CIENT., DESP. E OUTR.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339132', 'descricao' => 'MATERIAL, BEM OU SERVICO P/ DISTRIB. GRATUITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339135', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339139', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA (INTRA)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339140', 'descricao' => 'SERVICOS DE TECNOLOGIA DA INFORMACAO E COMUNICACAO - PJ', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339147', 'descricao' => 'OBRIG.TRIBUT.E CONTRIB-OP.INTRA-ORCAMENTARIAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339162', 'descricao' => 'AQUISICAO DE PRODUTOS PARA REVENDA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339191', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339192', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339193', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339196', 'descricao' => 'RESSARCIMENTO DE DESP. DE PESSOAL REQUISITADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339198', 'descricao' => 'COMPENSACOES AO RGPS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339199', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339200', 'descricao' => 'APLIC DIRETA DE RECUR RECEB DE OUTROS  ENTES DA FEDERA-CAO DECORRENTES DE DELEGACAO OU DESCENTRALIZACAO.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339214', 'descricao' => 'DIARIAS - CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339214', 'descricao' => 'DIARIAS - CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339218', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339218', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339220', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339220', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339230', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339232', 'descricao' => 'MATERIAL, BEM OU SERVICO PARA DISTRIBUICAO GRATUITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339233', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339235', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339236', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339239', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339292', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339299', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339300', 'descricao' => 'APLICACAO DIRETA - CONS PUB ENTE PARTICIPE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339330', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339332', 'descricao' => 'MATERIAL, BEM OU SERVICO PARA DIST GRATUITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339339', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PJ', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339400', 'descricao' => 'APLIC DIRETA - CONS PUB ENTE NAO PARTICIPE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339430', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339432', 'descricao' => 'MATERIAL, BEM OU SERVICO PARA DIST GRATUITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339439', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PJ', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339500', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339504', 'descricao' => 'CONTRATACAO POR TEMPO DETERMINADO LC 141/2012', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339508', 'descricao' => 'OUTROS BENEF.ASSIST. DO SERVIDOR E DO MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339514', 'descricao' => 'DIARIAS - CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339518', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339520', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339530', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339531', 'descricao' => 'PREMIACOES CULTURAIS, ARTISTICAS, CIENTIFICAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339532', 'descricao' => 'MATERIAL, BEM OU SERVICO PARA DIST.GRATUITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339533', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339534', 'descricao' => 'OUTRAS DESPESAS DE PESSOAL - TERCEIRIZACAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339535', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339536', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339537', 'descricao' => 'LOCACAO DE MAO-DE-OBRA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339538', 'descricao' => 'ARRENDAMENTO MERCANTIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339539', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339541', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339545', 'descricao' => 'SUBVENCOES ECONOMICAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339546', 'descricao' => 'AUXILIO-ALIMENTACAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339547', 'descricao' => 'OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339548', 'descricao' => 'OUTROS AUXILIOS FINANCEIROS A PESSOAS FISICAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339549', 'descricao' => 'AUXILIO-TRANSPORTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339567', 'descricao' => 'DEPOSITOS COMPULSORIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339591', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339593', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339596', 'descricao' => 'RESSARCIMENTO DESPESAS PESSOAL REQUISITADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339600', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339604', 'descricao' => 'CONTRATACAO POR TEMPO DETERMINADO LC 141/2012', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339608', 'descricao' => 'OUTROS BENEF.ASSIST. DO SERVIDOR E DO MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339614', 'descricao' => 'DIARIAS - CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339618', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339620', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339630', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339631', 'descricao' => 'PREMIACOES CULTURAIS, ARTISTICAS, CIENTIFICAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339632', 'descricao' => 'MATERIAL, BEM OU SERVICO PARA DIST.GRATUITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339633', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339634', 'descricao' => 'OUTRAS DESPESAS DE PESSOAL - TERCEIRIZACAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339635', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339636', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339637', 'descricao' => 'LOCACAO DE MAO-DE-OBRA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339638', 'descricao' => 'ARRENDAMENTO MERCANTIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339639', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339641', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339645', 'descricao' => 'SUBVENCOES ECONOMICAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339646', 'descricao' => 'AUXILIO-ALIMENTACAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339647', 'descricao' => 'OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339648', 'descricao' => 'OUTROS AUXILIOS FINANCEIROS A PESSOAS FISICAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339649', 'descricao' => 'AUXILIO-TRANSPORTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339667', 'descricao' => 'DEPOSITOS COMPULSORIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339691', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339693', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339696', 'descricao' => 'RESSARCIMENTO DESPESAS PESSOAL REQUISITADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339900', 'descricao' => 'A DEFINIR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '339999', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '400000', 'descricao' => 'DESPESAS DE CAPITAL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '440000', 'descricao' => 'INVESTIMENTOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '442042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443000', 'descricao' => 'TRANSFERENCIAS A ESTADOS E DISTRITO FEDERAL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443020', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443051', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443052', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443061', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443100', 'descricao' => 'TRANSFERENCIAS A ESTADOS E DF - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443141', 'descricao' => 'CONTRIBUICOES - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443142', 'descricao' => 'AUXILIOS - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443192', 'descricao' => 'DESPESAS DE EXER. ANTERIORES FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443200', 'descricao' => 'EXECUCAO ORCAMENTARIA DELEGADA AOS ESTADOS/DF', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443220', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443251', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443252', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443292', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443500', 'descricao' => 'TRANSFERENCIAS FUNDO A FUNDO ART.24 LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443541', 'descricao' => 'CONTRIBUICOES (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443542', 'descricao' => 'AUXILIOS (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443600', 'descricao' => 'TRANSFERENCIAS FUNDO A FUNDO ART.25 LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443641', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443642', 'descricao' => 'AUXILIOS (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '443692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444000', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444014', 'descricao' => 'DIARIAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444051', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444052', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444091', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444093', 'descricao' => 'INDENIZACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444100', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444141', 'descricao' => 'CONTRIBUICOES - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444142', 'descricao' => 'AUXILIOS - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444192', 'descricao' => 'DESPESAS DE EXERC. ANTERIORES FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444200', 'descricao' => 'EXECUCAO ORCAMENTARIA DELEGADA A MUNICIPIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444251', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444252', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444292', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444500', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS ART.24 LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444541', 'descricao' => 'CONTRIBUICOES (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444542', 'descricao' => 'AUXILIOS (ACOES E SERVICOS PUBLICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444600', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS ART.25 LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444641', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444642', 'descricao' => 'AUXILIOS (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '444692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445000', 'descricao' => 'TRANSF. A INST. PRIVADAS_S/ FINS LUCRATIVOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445014', 'descricao' => 'DIARIAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445030', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445036', 'descricao' => 'SERVICOS DE TERCEIROS - PESSOA FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445039', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445047', 'descricao' => 'OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445051', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '445052', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '446000', 'descricao' => 'TRANSF. A INST. PRIVADAS COM FINS LUCRATIVOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '446041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '446042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447000', 'descricao' => 'TRANSF. A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447100', 'descricao' => 'TRANSF.CONSORC.PUB.MEDIANTE CONTRATO RATEIO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447141', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447142', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447170', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447200', 'descricao' => 'EXECUCAO ORCAM.DELEGADA A CONSORCIOS PUBLICOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447251', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447300', 'descricao' => 'TRANSF.CONSOR.PUB.ART.24 LC 141/12 œœ 1º E 2º', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447370', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447400', 'descricao' => 'TRANSFERENCIA A CONSORCIOS PULBICOS LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447470', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447500', 'descricao' => 'TRANSF.A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447541', 'descricao' => 'CONTRIBUICOES (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447542', 'descricao' => 'AUXILIOS (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447600', 'descricao' => 'TRANSF.A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447641', 'descricao' => 'CONTRIBUICOES (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '447642', 'descricao' => 'AUXILIOS (ACOES E SERVICOS DE SAUDE)', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '448000', 'descricao' => 'TRANSFERENCIAS AO EXTERIOR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '448039', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '448041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '448042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '448051', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '448052', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449000', 'descricao' => 'APLICACOES DIRETAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449004', 'descricao' => 'CONTRATACAO POR TEMPO DETERMINADO - PES.CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449014', 'descricao' => 'DIARIAS - PESSOAL CIVIL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449015', 'descricao' => 'DIARIAS - PESSOAL MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449017', 'descricao' => 'OUTRAS DESPESAS VARIAVEIS - PESSOAL MILITAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449018', 'descricao' => 'AUXILIO FINANCEIRO A ESTUDANTES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449020', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449030', 'descricao' => 'MATERIAL DE CONSUMO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449033', 'descricao' => 'PASSAGENS E DESPESAS COM LOCOMOCAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449035', 'descricao' => 'SERVICOS DE CONSULTORIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449036', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS - P.FISICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449037', 'descricao' => 'LOCACAO DE MAO-DE-OBRA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449039', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS- PESSOA JURIDICA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449040', 'descricao' => 'SERVICOS DE TECNOLOGIA DA INFORMACAO E COMUNICACAO - PJ', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449046', 'descricao' => 'AUXILIO-ALIMENTACAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449047', 'descricao' => 'OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449051', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449052', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449061', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449091', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449093', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449095', 'descricao' => 'INDENIZACAO PELA EXECUCAO TRABALHOS DE CAMPO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449099', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449100', 'descricao' => 'APLICACOES DIRETAS - OP. INTRA-ORCAMENTARIAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449139', 'descricao' => 'OUTROS SERVICOS DE TERCEIROS PJ - OP.INT.ORC.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449147', 'descricao' => 'OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449151', 'descricao' => 'OBRAS E INSTALACOES - OP.INT.ORC.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449152', 'descricao' => 'EQUIP.E MATERIAL PERMANENTE - OP.INTRA-ORC.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449161', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449191', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449200', 'descricao' => 'APLICACAO DIRETA DE RECURSOS  RECEBIDOS DE OUTROS ENTESDA FEDERACAO DECORRENTES DE DELEGACAO/DESCENTRALIZACAO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449220', 'descricao' => 'AUXILIO FINANCEIRO A PESQUISADORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449251', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449252', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449299', 'descricao' => 'A CLASSIFICAR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449300', 'descricao' => 'APLICACAO DIRETA - CONS PUB ENTE PARTICIPE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449351', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449352', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449400', 'descricao' => 'APLIC DIRETA - CONS PUB ENTE NAO PARTICIPE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449451', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449452', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449500', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449551', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449552', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449561', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449591', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449593', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449600', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449651', 'descricao' => 'OBRAS E INSTALACOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449652', 'descricao' => 'EQUIPAMENTOS E MATERIAL PERMANENTE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449661', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449691', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449693', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '449900', 'descricao' => 'A DEFINIR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '450000', 'descricao' => 'INVERSOES FINANCEIRAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453000', 'descricao' => 'TRANSFER. A ESTADOS E AO DISTRITO FEDERAL', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453061', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453064', 'descricao' => 'AQUISICAO TIT.REPRES.DE CAP. JA INTEGRALIZADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453065', 'descricao' => 'CONSTITUICAO OU AUMENTO DE CAPITAL DE EMPRESA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453066', 'descricao' => 'CONCESSAO DE EMPRESTIMOS E FINANCIAMENTOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453100', 'descricao' => 'TRANSFER. A ESTADOS E DF - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453141', 'descricao' => 'CONTRIBUICOES - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453142', 'descricao' => 'AUXILIOS - FUNDO A FUNDO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '453200', 'descricao' => 'EXECUCAO ORCAMENTARIA DELEGADA AOS ESTADOS/DF', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '454000', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '454041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '454042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '454066', 'descricao' => 'CONCESSAO DE EMPRESTIMOS E FINANCIAMENTOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '454200', 'descricao' => 'EXECUCAO ORCAMENTARIA DELEGADA A MUNICIPIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '455000', 'descricao' => 'TRANSF. A INST. PRIVADAS S/ FINS LUCRATIVOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '455066', 'descricao' => 'CONCESSAO DE EMPRESTIMOS E FINANCIAMENTOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457000', 'descricao' => 'TRANSF. A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457041', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457042', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457100', 'descricao' => 'TRANSF.CONSORC.PUB.MEDIANTE CONTRATO RATEIO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457141', 'descricao' => 'CONTRIBUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457142', 'descricao' => 'AUXILIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457170', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457200', 'descricao' => 'EXECUCAO ORCAM.DELEGADA A CONSORCIOS PUBLICOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457300', 'descricao' => 'TRANSF.CONSOR.PUB.ART.24 LC 141/12 œœ 1º E 2º', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457370', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457400', 'descricao' => 'TRANSFERENCIA A CONSORCIOS PULBICOS LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '457470', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459000', 'descricao' => 'APLICACOES DIRETAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459061', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459062', 'descricao' => 'AQUISICAO DE BENS PARA REVENDA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459063', 'descricao' => 'AQUISICAO DE TITULOS DE CREDITO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459064', 'descricao' => 'AQUISICAO TIT.REPRES.DE CAP.JA INTEGRALIZADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459065', 'descricao' => 'CONSTIT. OU AUMENTO DE CAPITAL DE EMPRESAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459066', 'descricao' => 'CONCESSAO DE EMPRESTIMOS E FINANCIAMENTOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459067', 'descricao' => 'DEPOSITOS COMPULSORIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459084', 'descricao' => 'PARTICIPACAO EM FUNDOS, ORGANISMOS OU ENTIDADES ASSEME-LHADAS, NACIONAIS E INTERNACIONAIS.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459091', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459093', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459100', 'descricao' => 'APLICACOES DIRETAS - OPERACOES INTERNAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459161', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459162', 'descricao' => 'AQUISICAO DE BENS PARA REVENDA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459165', 'descricao' => 'CONSTIT. OU AUMENTO DE CAPITAL DE EMPRESAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459166', 'descricao' => 'CONCESSAO DE EMPRESTIMOS E FINANCIAMENTOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459184', 'descricao' => 'PARTICIPACAO EM FUNDOS, ORGANISMOS OU ENTIDADES ASSEME-LHADAS, NACIONAIS E INTERNACIONAIS.', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459191', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459192', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459500', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459561', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459567', 'descricao' => 'DEPOSITOS COMPULSORIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459591', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459593', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459600', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459661', 'descricao' => 'AQUISICAO DE IMOVEIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459667', 'descricao' => 'DEPOSITOS COMPULSORIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459691', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459693', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '459900', 'descricao' => 'A DEFINIR', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '460000', 'descricao' => 'AMORTIZACAO/REFINANCIAMENTO DA DIVIDA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '467000', 'descricao' => 'TRANSF. A INSTITUICOES MULTIGOVERNAMENTAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '467100', 'descricao' => 'TRANSF.CONSORC.PUB.MEDIANTE CONTRATO RATEIO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '467300', 'descricao' => 'TRANSF.CONSOR.PUB.ART.24 LC 141/12 œœ 1º E 2º', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '467370', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '467400', 'descricao' => 'TRANSFERENCIA A CONSORCIOS PULBICOS LC 141/12', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '467470', 'descricao' => 'RATEIO PELA PARTICIPACAO EM CONSORCIO PUBLICO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469000', 'descricao' => 'APLICACOES DIRETAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469026', 'descricao' => 'OBRIGACOES DECORRENTES DE POLITICA MONETARIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469071', 'descricao' => 'PRINCIPAL DA DIVIDA CONTRATUAL RESGATADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469072', 'descricao' => 'PRINCIPAL DA DIVIDA MOBILIARIA RESGATADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469073', 'descricao' => 'CORREC.MONET.E CAMBIAL DA DIVIDA POR CONTRATO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469074', 'descricao' => 'COR.MONET.E CAMBIAL DA DIV.MOBIL.RESGATADA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469075', 'descricao' => 'COR.MONET.OPER.DE CRED.POR ANTEC.DA RECEITA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469076', 'descricao' => 'PRINCIPAL CORRIGIDO DA DIV.MOB.REFINANCIADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469077', 'descricao' => 'PRINCIPAL CORRIGIDO DIVIDA CONTR.REFINANCIADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469091', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469092', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469093', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469176', 'descricao' => 'PRINCIPAL CORRIGIDO DA DIV.MOB.REFINANCIADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469500', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469571', 'descricao' => 'PRINCIPAL DA DIVIDA CONTRATUAL RESGATADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469573', 'descricao' => 'CM OU CAMBIAL DA DIVIDA CONTRATUAL RESGATADA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469577', 'descricao' => 'PRINCIPAL CORRIGIDO DA DIVIDA CONTRATUAL RESG', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469591', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469592', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469593', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469600', 'descricao' => 'APLICACAO DIRETA - ACOES E SERVICOS DE SAUDE', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469671', 'descricao' => 'PRINCIPAL DA DIVIDA CONTRATUAL RESGATADO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469673', 'descricao' => 'CM OU CAMBIAL DA DIVIDA CONTRATUAL RESGATADA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469677', 'descricao' => 'PRINCIPAL CORRIGIDO DA DIVIDA CONTRATUAL RESG', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469691', 'descricao' => 'SENTENCAS JUDICIAIS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469692', 'descricao' => 'DESPESAS DE EXERCICIOS ANTERIORES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '469693', 'descricao' => 'INDENIZACOES E RESTITUICOES', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '800000', 'descricao' => 'PASSIVO FINANCEIRO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '880000', 'descricao' => 'PASSIVO FINANCEIRO', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '900000', 'descricao' => 'RESERVA DE CONTINGENCIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '990000', 'descricao' => 'RESERVA DE CONTINGENCIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '994000', 'descricao' => 'TRANSFERENCIAS A MUNICIPIOS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '999000', 'descricao' => 'APLICACOES DIRETAS', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '999900', 'descricao' => 'RESERVA DE CONTINGENCIA', 'situacao' => 1]);
        DB::table('naturezadespesa')->insert(['codigo' => '999999', 'descricao' => 'RESERVA DE CONTINGENCIA', 'situacao' => 1]);


    }
}
