# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  conta-postgres-data:
    driver: local

services:
  # Postgres (9.6)
  postgres:
    image: postgres:9.6
    container_name: conta-postgres
    volumes:
      - conta-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=conta
      - POSTGRES_DB=conta
      - POSTGRES_USER=conta

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-nginx
    container_name: conta-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
