site_name: COMPRASNET CONTRATOS

nav:
  - 'Apresentação': 'index.md'
  - 'Funcionalidades existentes e previsões': 'funcionalidades.md'
  - 'Orientações Iniciais': 'orientacoes.md'
  - 'Como acessar': 'acesso.md'
  - 'Manuais do sistema': 'manuaisDoSistema.md'
  - 'Grupos de Usuários': 'grupos.md'
  - 'Licença': 'licenca.md'

theme:
    name: readthedocs
    titles_only: true
    highlightjs: false
    include_homepage_in_sidebar: true
    custom_dir: docs/
    include_search_page: false

markdown_extensions:
  - extra
  - toc:
      permalink: '#'
      separator: "_"