<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->call(ActivityLogTableSeeder::class);
        $this->call(ActivityLogExpurgoTableSeeder::class);
        $this->call(AppVersionTableSeeder::class);
        $this->call(ApropriacoesTableSeeder::class);
        $this->call(ApropriacoesFasesTableSeeder::class);
        $this->call(ApropriacoesImportacaoTableSeeder::class);
        $this->call(ApropriacoesNotaEmpenhoTableSeeder::class);
        $this->call(ApropriacoesSituacaoTableSeeder::class);
        $this->call(CalendareventsTableSeeder::class);
        $this->call(CatmatseratualizacaoTableSeeder::class);
        $this->call(CatmatsergruposTableSeeder::class);
        $this->call(CatmatseritensTableSeeder::class);
        $this->call(CentrocustoTableSeeder::class);
        $this->call(CodigoitensTableSeeder::class);
        $this->call(CodigosTableSeeder::class);
        $this->call(ComunicaTableSeeder::class);
        $this->call(ContratoArquivosTableSeeder::class);
        $this->call(ContratocronogramaTableSeeder::class);
        $this->call(ContratodespesaacessoriaTableSeeder::class);
        $this->call(ContratoempenhosTableSeeder::class);
        $this->call(ContratofaturaEmpenhosTableSeeder::class);
        $this->call(ContratofaturasTableSeeder::class);
        $this->call(ContratogarantiasTableSeeder::class);
        $this->call(ContratohistoricoTableSeeder::class);
        $this->call(ContratoitensTableSeeder::class);
        $this->call(ContratoocorrenciasTableSeeder::class);
        $this->call(ContratoprepostoTableSeeder::class);
        $this->call(ContratoresponsaveisTableSeeder::class);
        $this->call(ContratosTableSeeder::class);
        $this->call(ContratoterceirizadosTableSeeder::class);
        $this->call(DocumentosiafiTableSeeder::class);
        $this->call(EmpenhodetalhadoTableSeeder::class);
        $this->call(EmpenhosTableSeeder::class);
        $this->call(ExecsfsituacaoTableSeeder::class);
        $this->call(FailedJobsTableSeeder::class);
        $this->call(FornecedoresTableSeeder::class);
        $this->call(ImportacoesTableSeeder::class);
        $this->call(InstalacoesTableSeeder::class);
        $this->call(JobsTableSeeder::class);
        $this->call(JustificativafaturaTableSeeder::class);
        $this->call(MigracaosistemacontaTableSeeder::class);
        $this->call(MigrationsTableSeeder::class);
        $this->call(ModelHasPermissionsTableSeeder::class);
        $this->call(ModelHasRolesTableSeeder::class);
        $this->call(NaturezadespesaTableSeeder::class);
        $this->call(NaturezasubitemTableSeeder::class);
        $this->call(OrgaoconfiguracaoTableSeeder::class);
        $this->call(OrgaosTableSeeder::class);
        $this->call(OrgaossuperioresTableSeeder::class);
        $this->call(OrgaosubcategoriasTableSeeder::class);
        $this->call(PermissionsTableSeeder::class);
        $this->call(PlanointernoTableSeeder::class);
        $this->call(RhddpTableSeeder::class);
        $this->call(RhddpdetalhadoTableSeeder::class);
        $this->call(RhrubricaTableSeeder::class);
        $this->call(RhsituacaoTableSeeder::class);
        $this->call(RhsituacaoRhrubricaTableSeeder::class);
        $this->call(RoleHasPermissionsTableSeeder::class);
        $this->call(RolesTableSeeder::class);
        $this->call(SaldohistoricoitensTableSeeder::class);
        $this->call(SfacrescimoTableSeeder::class);
        $this->call(SfcentrocustoTableSeeder::class);
        $this->call(SfcertificadoTableSeeder::class);
        $this->call(SfdadosbasicosTableSeeder::class);
        $this->call(SfdeducaoEncargoDadospagtoTableSeeder::class);
        $this->call(SfdespesaanularTableSeeder::class);
        $this->call(SfdespesaanularitemTableSeeder::class);
        $this->call(SfdocorigemTableSeeder::class);
        $this->call(SfdomiciliobancarioTableSeeder::class);
        $this->call(SfitemrecolhimentoTableSeeder::class);
        $this->call(SfnonceTableSeeder::class);
        $this->call(SfoutroslancTableSeeder::class);
        $this->call(SfpadraoTableSeeder::class);
        $this->call(SfpcoTableSeeder::class);
        $this->call(SfpcoitemTableSeeder::class);
        $this->call(SfpredocTableSeeder::class);
        $this->call(SfpsoTableSeeder::class);
        $this->call(SfpsoitemTableSeeder::class);
        $this->call(SfrelitemdedTableSeeder::class);
        $this->call(SfrelitemdespanularTableSeeder::class);
        $this->call(SfrelitemvlrccTableSeeder::class);
        $this->call(SubrogacoesTableSeeder::class);
        $this->call(TipolistafaturaTableSeeder::class);
        $this->call(UnidadeconfiguracaoTableSeeder::class);
        $this->call(UnidadesTableSeeder::class);
        $this->call(UnidadesusersTableSeeder::class);
        $this->call(UsersTableSeeder::class);
    }
}
