<?php

use Illuminate\Database\Seeder;

class RhsituacaoTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('rhsituacao')->insert(array (
            0 =>
            array (
                'id' => 55000001,
                'execsfsituacao_id' => 55000009,
                'nd' => '31900101',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 55000002,
                'execsfsituacao_id' => 55000213,
                'nd' => '31900101',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 55000003,
                'execsfsituacao_id' => 55000009,
                'nd' => '31900101',
                'vpd' => '321110300',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 55000004,
                'execsfsituacao_id' => 55000213,
                'nd' => '31900101',
                'vpd' => '321110300',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 55000005,
                'execsfsituacao_id' => 55000009,
                'nd' => '31900105',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 55000006,
                'execsfsituacao_id' => 55000213,
                'nd' => '31900105',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 55000007,
                'execsfsituacao_id' => 55000009,
                'nd' => '31900109',
                'vpd' => '321119900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 55000008,
                'execsfsituacao_id' => 55000213,
                'nd' => '31900109',
                'vpd' => '321119900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 55000009,
                'execsfsituacao_id' => 55000009,
                'nd' => '31900116',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 55000010,
                'execsfsituacao_id' => 55000213,
                'nd' => '31900116',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 55000011,
                'execsfsituacao_id' => 55000009,
                'nd' => '31900134',
                'vpd' => '321110300',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 55000012,
                'execsfsituacao_id' => 55000213,
                'nd' => '31900134',
                'vpd' => '321110300',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 55000013,
                'execsfsituacao_id' => 55000009,
                'nd' => '31900187',
                'vpd' => '321110800',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 55000014,
                'execsfsituacao_id' => 55000213,
                'nd' => '31900187',
                'vpd' => '321110800',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 55000015,
                'execsfsituacao_id' => 55000010,
                'nd' => '31900301',
                'vpd' => '322110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 55000016,
                'execsfsituacao_id' => 55000214,
                'nd' => '31900301',
                'vpd' => '322110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 55000017,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901101',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'id' => 55000018,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901101',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'id' => 55000019,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901104',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'id' => 55000020,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901104',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'id' => 55000021,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901105',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 =>
            array (
                'id' => 55000022,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901105',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 =>
            array (
                'id' => 55000023,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901106',
                'vpd' => '311110900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 =>
            array (
                'id' => 55000024,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901106',
                'vpd' => '311110900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 =>
            array (
                'id' => 55000025,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901107',
                'vpd' => '311110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'id' => 55000026,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901107',
                'vpd' => '311110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 55000027,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901107',
                'vpd' => '311110200',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'id' => 55000028,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901107',
                'vpd' => '311110200',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 =>
            array (
                'id' => 55000029,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901110',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 55000030,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901110',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'id' => 55000031,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901110',
                'vpd' => '311110300',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 55000032,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901110',
                'vpd' => '311110300',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 =>
            array (
                'id' => 55000033,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901131',
                'vpd' => '311110400',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 55000034,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901131',
                'vpd' => '311110400',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'id' => 55000035,
                'execsfsituacao_id' => 55000012,
                'nd' => '31901131',
                'vpd' => '311210400',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 55000036,
                'execsfsituacao_id' => 55000215,
                'nd' => '31901131',
                'vpd' => '311210400',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array (
                'id' => 55000037,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901135',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 =>
            array (
                'id' => 55000038,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901135',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'id' => 55000039,
                'execsfsituacao_id' => 55000012,
                'nd' => '31901136',
                'vpd' => '311210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 55000040,
                'execsfsituacao_id' => 55000215,
                'nd' => '31901136',
                'vpd' => '311210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 =>
            array (
                'id' => 55000041,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901136',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'id' => 55000042,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901136',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 =>
            array (
                'id' => 55000043,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901136',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 =>
            array (
                'id' => 55000044,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901136',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 =>
            array (
                'id' => 55000045,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901136',
                'vpd' => '311110400',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 =>
            array (
                'id' => 55000046,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901136',
                'vpd' => '311110400',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 =>
            array (
                'id' => 55000047,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901137',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 =>
            array (
                'id' => 55000048,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901137',
                'vpd' => '311110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 =>
            array (
                'id' => 55000049,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901142',
                'vpd' => '311110500',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 =>
            array (
                'id' => 55000050,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901142',
                'vpd' => '311110500',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 =>
            array (
                'id' => 55000051,
                'execsfsituacao_id' => 55000009,
                'nd' => '31901142',
                'vpd' => '321110400',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 =>
            array (
                'id' => 55000052,
                'execsfsituacao_id' => 55000213,
                'nd' => '31901142',
                'vpd' => '321110400',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 =>
            array (
                'id' => 55000053,
                'execsfsituacao_id' => 55000012,
                'nd' => '31901142',
                'vpd' => '311210500',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 =>
            array (
                'id' => 55000054,
                'execsfsituacao_id' => 55000215,
                'nd' => '31901142',
                'vpd' => '311210500',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55000055,
                'execsfsituacao_id' => 55000028,
                'nd' => '31901143',
                'vpd' => '113110101',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 =>
            array (
                'id' => 55000056,
                'execsfsituacao_id' => 55000225,
                'nd' => '31901143',
                'vpd' => '113110101',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 =>
            array (
                'id' => 55000057,
                'execsfsituacao_id' => 55000028,
                'nd' => '31901143',
                'vpd' => '113110101',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 =>
            array (
                'id' => 55000058,
                'execsfsituacao_id' => 55000225,
                'nd' => '31901143',
                'vpd' => '113110101',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 =>
            array (
                'id' => 55000059,
                'execsfsituacao_id' => 55000029,
                'nd' => '31901145',
                'vpd' => '113110102',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 =>
            array (
                'id' => 55000060,
                'execsfsituacao_id' => 55000226,
                'nd' => '31901145',
                'vpd' => '113110102',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 =>
            array (
                'id' => 55000061,
                'execsfsituacao_id' => 55000029,
                'nd' => '31901145',
                'vpd' => '113110102',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 =>
            array (
                'id' => 55000062,
                'execsfsituacao_id' => 55000226,
                'nd' => '31901145',
                'vpd' => '113110102',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 =>
            array (
                'id' => 55000063,
                'execsfsituacao_id' => 55000030,
                'nd' => '31901146',
                'vpd' => '113110105',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 =>
            array (
                'id' => 55000064,
                'execsfsituacao_id' => 55000227,
                'nd' => '31901146',
                'vpd' => '113110105',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 =>
            array (
                'id' => 55000065,
                'execsfsituacao_id' => 55000030,
                'nd' => '31901146',
                'vpd' => '113110105',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 =>
            array (
                'id' => 55000066,
                'execsfsituacao_id' => 55000227,
                'nd' => '31901146',
                'vpd' => '113110105',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 =>
            array (
                'id' => 55000067,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901174',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 =>
            array (
                'id' => 55000068,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901174',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 =>
            array (
                'id' => 55000069,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901632',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 =>
            array (
                'id' => 55000070,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901632',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 =>
            array (
                'id' => 55000071,
                'execsfsituacao_id' => 55000012,
                'nd' => '31901632',
                'vpd' => '311210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 =>
            array (
                'id' => 55000072,
                'execsfsituacao_id' => 55000215,
                'nd' => '31901632',
                'vpd' => '311210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 =>
            array (
                'id' => 55000073,
                'execsfsituacao_id' => 55000006,
                'nd' => '31909114',
                'vpd' => '311110900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 =>
            array (
                'id' => 55000074,
                'execsfsituacao_id' => 55000211,
                'nd' => '31909114',
                'vpd' => '311110900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 =>
            array (
                'id' => 55000075,
                'execsfsituacao_id' => 55000009,
                'nd' => '31909115',
                'vpd' => '321110900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 =>
            array (
                'id' => 55000076,
                'execsfsituacao_id' => 55000213,
                'nd' => '31909115',
                'vpd' => '321110900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 =>
            array (
                'id' => 55000077,
                'execsfsituacao_id' => 55000006,
                'nd' => '31909211',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 =>
            array (
                'id' => 55000078,
                'execsfsituacao_id' => 55000211,
                'nd' => '31909211',
                'vpd' => '311110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 =>
            array (
                'id' => 55000079,
                'execsfsituacao_id' => 55000006,
                'nd' => '31909416',
                'vpd' => '311110800',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 =>
            array (
                'id' => 55000080,
                'execsfsituacao_id' => 55000211,
                'nd' => '31909416',
                'vpd' => '311110800',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 =>
            array (
                'id' => 55000081,
                'execsfsituacao_id' => 55000008,
                'nd' => '33900805',
                'vpd' => '313119900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 =>
            array (
                'id' => 55000082,
                'execsfsituacao_id' => 55000212,
                'nd' => '33900805',
                'vpd' => '313119900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 =>
            array (
                'id' => 55000083,
                'execsfsituacao_id' => 55000008,
                'nd' => '33900809',
                'vpd' => '313110600',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 =>
            array (
                'id' => 55000084,
                'execsfsituacao_id' => 55000212,
                'nd' => '33900809',
                'vpd' => '313110600',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 =>
            array (
                'id' => 55000085,
                'execsfsituacao_id' => 55000014,
                'nd' => '33900809',
                'vpd' => '313210600',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 =>
            array (
                'id' => 55000086,
                'execsfsituacao_id' => 55000216,
                'nd' => '33900809',
                'vpd' => '313210600',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 =>
            array (
                'id' => 55000087,
                'execsfsituacao_id' => 55000014,
                'nd' => '33903607',
                'vpd' => '313210400',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 =>
            array (
                'id' => 55000088,
                'execsfsituacao_id' => 55000216,
                'nd' => '33903607',
                'vpd' => '313210400',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 =>
            array (
                'id' => 55000089,
                'execsfsituacao_id' => 55000014,
                'nd' => '33903607',
                'vpd' => '313219900',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 =>
            array (
                'id' => 55000090,
                'execsfsituacao_id' => 55000216,
                'nd' => '33903607',
                'vpd' => '313219900',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 =>
            array (
                'id' => 55000091,
                'execsfsituacao_id' => 55000008,
                'nd' => '33903628',
                'vpd' => '313119900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 =>
            array (
                'id' => 55000092,
                'execsfsituacao_id' => 55000212,
                'nd' => '33903628',
                'vpd' => '313119900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 =>
            array (
                'id' => 55000093,
                'execsfsituacao_id' => 55000008,
                'nd' => '33904601',
                'vpd' => '313110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 =>
            array (
                'id' => 55000094,
                'execsfsituacao_id' => 55000212,
                'nd' => '33904601',
                'vpd' => '313110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 =>
            array (
                'id' => 55000095,
                'execsfsituacao_id' => 55000014,
                'nd' => '33904601',
                'vpd' => '313210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 =>
            array (
                'id' => 55000096,
                'execsfsituacao_id' => 55000216,
                'nd' => '33904601',
                'vpd' => '313210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 =>
            array (
                'id' => 55000097,
                'execsfsituacao_id' => 55000008,
                'nd' => '33904601',
                'vpd' => '313110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 =>
            array (
                'id' => 55000098,
                'execsfsituacao_id' => 55000212,
                'nd' => '33904601',
                'vpd' => '313110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 =>
            array (
                'id' => 55000099,
                'execsfsituacao_id' => 55000008,
                'nd' => '33904901',
                'vpd' => '313110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 =>
            array (
                'id' => 55000100,
                'execsfsituacao_id' => 55000212,
                'nd' => '33904901',
                'vpd' => '313110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 =>
            array (
                'id' => 55000101,
                'execsfsituacao_id' => 55000014,
                'nd' => '33904901',
                'vpd' => '313210200',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 =>
            array (
                'id' => 55000102,
                'execsfsituacao_id' => 55000216,
                'nd' => '33904901',
                'vpd' => '313210200',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 =>
            array (
                'id' => 55000103,
                'execsfsituacao_id' => 55000008,
                'nd' => '33904901',
                'vpd' => '313110200',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 =>
            array (
                'id' => 55000104,
                'execsfsituacao_id' => 55000212,
                'nd' => '33904901',
                'vpd' => '313110200',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 =>
            array (
                'id' => 55000105,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909246',
                'vpd' => '313110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 =>
            array (
                'id' => 55000106,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909246',
                'vpd' => '313110100',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 =>
            array (
                'id' => 55000107,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909293',
                'vpd' => '313110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 =>
            array (
                'id' => 55000108,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909293',
                'vpd' => '313110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 =>
            array (
                'id' => 55000109,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909305',
                'vpd' => '313110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 =>
            array (
                'id' => 55000110,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909305',
                'vpd' => '313110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 =>
            array (
                'id' => 55000111,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909307',
                'vpd' => '313110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 =>
            array (
                'id' => 55000112,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909307',
                'vpd' => '313110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 =>
            array (
                'id' => 55000113,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909308',
                'vpd' => '313110500',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 =>
            array (
                'id' => 55000114,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909308',
                'vpd' => '313110500',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 =>
            array (
                'id' => 55000115,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909308',
                'vpd' => '313110500',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 =>
            array (
                'id' => 55000116,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909308',
                'vpd' => '313110500',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 =>
            array (
                'id' => 55000117,
                'execsfsituacao_id' => 55000014,
                'nd' => '33909308',
                'vpd' => '313210500',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 =>
            array (
                'id' => 55000118,
                'execsfsituacao_id' => 55000216,
                'nd' => '33909308',
                'vpd' => '313210500',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 =>
            array (
                'id' => 55000119,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909311',
                'vpd' => '313119900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 =>
            array (
                'id' => 55000120,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909311',
                'vpd' => '313119900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 =>
            array (
                'id' => 55000121,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909311',
                'vpd' => '313119900',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 =>
            array (
                'id' => 55000122,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909311',
                'vpd' => '313119900',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 =>
            array (
                'id' => 55000123,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901133',
                'vpd' => '311110400',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 =>
            array (
                'id' => 55000124,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901133',
                'vpd' => '311110400',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 =>
            array (
                'id' => 55000125,
                'execsfsituacao_id' => 55000012,
                'nd' => '31901133',
                'vpd' => '311210400',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 =>
            array (
                'id' => 55000126,
                'execsfsituacao_id' => 55000215,
                'nd' => '31901133',
                'vpd' => '311210400',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 =>
            array (
                'id' => 55000127,
                'execsfsituacao_id' => 55000010,
                'nd' => '31909199',
                'vpd' => '322110900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 =>
            array (
                'id' => 55000128,
                'execsfsituacao_id' => 55000214,
                'nd' => '31909199',
                'vpd' => '322110900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 =>
            array (
                'id' => 55000129,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909249',
                'vpd' => '313110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 =>
            array (
                'id' => 55000130,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909249',
                'vpd' => '313110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 =>
            array (
                'id' => 55000131,
                'execsfsituacao_id' => 55000118,
                'nd' => '0',
                'vpd' => '18806-9',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 =>
            array (
                'id' => 55000132,
                'execsfsituacao_id' => 55000118,
                'nd' => '0',
                'vpd' => '18806-9',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 =>
            array (
                'id' => 55000133,
                'execsfsituacao_id' => 55000118,
                'nd' => '0',
                'vpd' => '18806-9',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 =>
            array (
                'id' => 55000134,
                'execsfsituacao_id' => 55000094,
                'nd' => '0',
                'vpd' => '561',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 =>
            array (
                'id' => 55000135,
                'execsfsituacao_id' => 55000094,
                'nd' => '0',
                'vpd' => '561',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 =>
            array (
                'id' => 55000136,
                'execsfsituacao_id' => 55000094,
                'nd' => '0',
                'vpd' => '561',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 =>
            array (
                'id' => 55000137,
                'execsfsituacao_id' => 55000111,
                'nd' => '0',
                'vpd' => '2402',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 =>
            array (
                'id' => 55000138,
                'execsfsituacao_id' => 55000099,
                'nd' => '0',
                'vpd' => '1661',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 =>
            array (
                'id' => 55000139,
                'execsfsituacao_id' => 55000099,
                'nd' => '0',
                'vpd' => '1661',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 =>
            array (
                'id' => 55000140,
                'execsfsituacao_id' => 55000099,
                'nd' => '0',
                'vpd' => '1717',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 =>
            array (
                'id' => 55000141,
                'execsfsituacao_id' => 55000154,
                'nd' => '0',
                'vpd' => '218810127',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 =>
            array (
                'id' => 55000142,
                'execsfsituacao_id' => 55000154,
                'nd' => '0',
                'vpd' => '218810127',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 =>
            array (
                'id' => 55000143,
                'execsfsituacao_id' => 55000118,
                'nd' => '0',
                'vpd' => '28804-7',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 =>
            array (
                'id' => 55000144,
                'execsfsituacao_id' => 55000118,
                'nd' => '0',
                'vpd' => '28804-7',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 =>
            array (
                'id' => 55000145,
                'execsfsituacao_id' => 55000137,
                'nd' => '0',
                'vpd' => '218810122',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 =>
            array (
                'id' => 55000146,
                'execsfsituacao_id' => 55000137,
                'nd' => '0',
                'vpd' => '218810122',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 =>
            array (
                'id' => 55000147,
                'execsfsituacao_id' => 55000137,
                'nd' => '0',
                'vpd' => '218810122',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 =>
            array (
                'id' => 55000148,
                'execsfsituacao_id' => 55000152,
                'nd' => '0',
                'vpd' => '218810199',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 =>
            array (
                'id' => 55000149,
                'execsfsituacao_id' => 55000152,
                'nd' => '0',
                'vpd' => '218810199',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 =>
            array (
                'id' => 55000150,
                'execsfsituacao_id' => 55000152,
                'nd' => '0',
                'vpd' => '218810199',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 =>
            array (
                'id' => 55000151,
                'execsfsituacao_id' => 55000380,
                'nd' => '0',
                'vpd' => '311110600',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 =>
            array (
                'id' => 55000152,
                'execsfsituacao_id' => 55000382,
                'nd' => '0',
                'vpd' => '321110500',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            152 =>
            array (
                'id' => 55000153,
                'execsfsituacao_id' => 55000380,
                'nd' => '0',
                'vpd' => '311210600',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            153 =>
            array (
                'id' => 55000154,
                'execsfsituacao_id' => 55000381,
                'nd' => '0',
                'vpd' => '311110500',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            154 =>
            array (
                'id' => 55000155,
                'execsfsituacao_id' => 55000381,
                'nd' => '0',
                'vpd' => '321110400',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            155 =>
            array (
                'id' => 55000156,
                'execsfsituacao_id' => 55000381,
                'nd' => '0',
                'vpd' => '311210500',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            156 =>
            array (
                'id' => 55000157,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909293',
                'vpd' => '313110300',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            157 =>
            array (
                'id' => 55000158,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909293',
                'vpd' => '313110300',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            158 =>
            array (
                'id' => 55000159,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909293',
                'vpd' => '313110300',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            159 =>
            array (
                'id' => 55000160,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909293',
                'vpd' => '313110300',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            160 =>
            array (
                'id' => 55000161,
                'execsfsituacao_id' => 55000012,
                'nd' => '31901144',
                'vpd' => '311210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            161 =>
            array (
                'id' => 55000162,
                'execsfsituacao_id' => 55000215,
                'nd' => '31901144',
                'vpd' => '311210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            162 =>
            array (
                'id' => 55000163,
                'execsfsituacao_id' => 55000009,
                'nd' => '31900106',
                'vpd' => '321110400',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            163 =>
            array (
                'id' => 55000164,
                'execsfsituacao_id' => 55000213,
                'nd' => '31900106',
                'vpd' => '321110400',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            164 =>
            array (
                'id' => 55000165,
                'execsfsituacao_id' => 55000009,
                'nd' => '31909201',
                'vpd' => '321110500',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            165 =>
            array (
                'id' => 55000166,
                'execsfsituacao_id' => 55000213,
                'nd' => '31909201',
                'vpd' => '321110500',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            166 =>
            array (
                'id' => 55000167,
                'execsfsituacao_id' => 55000021,
                'nd' => '31901243',
                'vpd' => '311310300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            167 =>
            array (
                'id' => 55000168,
                'execsfsituacao_id' => 55000221,
                'nd' => '31901243',
                'vpd' => '311310300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            168 =>
            array (
                'id' => 55000169,
                'execsfsituacao_id' => 55000021,
                'nd' => '31901245',
                'vpd' => '311310500',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            169 =>
            array (
                'id' => 55000170,
                'execsfsituacao_id' => 55000221,
                'nd' => '31901245',
                'vpd' => '311310500',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            170 =>
            array (
                'id' => 55000171,
                'execsfsituacao_id' => 55000010,
                'nd' => '31900303',
                'vpd' => '322110200',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            171 =>
            array (
                'id' => 55000172,
                'execsfsituacao_id' => 55000214,
                'nd' => '31900303',
                'vpd' => '322110200',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            172 =>
            array (
                'id' => 55000173,
                'execsfsituacao_id' => 55000006,
                'nd' => '31909203',
                'vpd' => '311110900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            173 =>
            array (
                'id' => 55000174,
                'execsfsituacao_id' => 55000211,
                'nd' => '31909203',
                'vpd' => '311110900',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            174 =>
            array (
                'id' => 55000175,
                'execsfsituacao_id' => 55000009,
                'nd' => '31909291',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            175 =>
            array (
                'id' => 55000176,
                'execsfsituacao_id' => 55000213,
                'nd' => '31909291',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            176 =>
            array (
                'id' => 55000177,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901133',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            177 =>
            array (
                'id' => 55000178,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901133',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            178 =>
            array (
                'id' => 55000179,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909290',
                'vpd' => '313110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            179 =>
            array (
                'id' => 55000180,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909290',
                'vpd' => '313110300',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            180 =>
            array (
                'id' => 55000181,
                'execsfsituacao_id' => 55000008,
                'nd' => '33909208',
                'vpd' => '313110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            181 =>
            array (
                'id' => 55000182,
                'execsfsituacao_id' => 55000212,
                'nd' => '33909208',
                'vpd' => '313110200',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            182 =>
            array (
                'id' => 55000183,
                'execsfsituacao_id' => 55000006,
                'nd' => '31909203',
                'vpd' => '321110900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            183 =>
            array (
                'id' => 55000184,
                'execsfsituacao_id' => 55000211,
                'nd' => '31909203',
                'vpd' => '321110900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            184 =>
            array (
                'id' => 55000185,
                'execsfsituacao_id' => 55000006,
                'nd' => '31909211',
                'vpd' => '311210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            185 =>
            array (
                'id' => 55000186,
                'execsfsituacao_id' => 55000211,
                'nd' => '31909211',
                'vpd' => '311210100',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            186 =>
            array (
                'id' => 55000187,
                'execsfsituacao_id' => 55000111,
                'nd' => '0',
                'vpd' => '2402',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            187 =>
            array (
                'id' => 55000188,
                'execsfsituacao_id' => 55000111,
                'nd' => '0',
                'vpd' => '2402',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            188 =>
            array (
                'id' => 55000189,
                'execsfsituacao_id' => 55000118,
                'nd' => '0',
                'vpd' => '28804-7',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            189 =>
            array (
                'id' => 55000190,
                'execsfsituacao_id' => 55000118,
                'nd' => '0',
                'vpd' => '28804-7',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            190 =>
            array (
                'id' => 55000191,
                'execsfsituacao_id' => 55000099,
                'nd' => '0',
                'vpd' => '1661',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            191 =>
            array (
                'id' => 55000192,
                'execsfsituacao_id' => 55000099,
                'nd' => '0',
                'vpd' => '1661',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            192 =>
            array (
                'id' => 55000193,
                'execsfsituacao_id' => 55000094,
                'nd' => '0',
                'vpd' => '561',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            193 =>
            array (
                'id' => 55000194,
                'execsfsituacao_id' => 55000094,
                'nd' => '0',
                'vpd' => '561',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            194 =>
            array (
                'id' => 55000195,
                'execsfsituacao_id' => 55000094,
                'nd' => '0',
                'vpd' => '561',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            195 =>
            array (
                'id' => 55000196,
                'execsfsituacao_id' => 55000012,
                'nd' => '31901632',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            196 =>
            array (
                'id' => 55000197,
                'execsfsituacao_id' => 55000215,
                'nd' => '31901632',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            197 =>
            array (
                'id' => 55000198,
                'execsfsituacao_id' => 55000028,
                'nd' => '31901143',
                'vpd' => '113110101',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            198 =>
            array (
                'id' => 55000199,
                'execsfsituacao_id' => 55000225,
                'nd' => '31901143',
                'vpd' => '113110101',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            199 =>
            array (
                'id' => 55000200,
                'execsfsituacao_id' => 55000006,
                'nd' => '31909203',
                'vpd' => '321210900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            200 =>
            array (
                'id' => 55000201,
                'execsfsituacao_id' => 55000211,
                'nd' => '31909203',
                'vpd' => '321210900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            201 =>
            array (
                'id' => 55000202,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901101',
                'vpd' => '311110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            202 =>
            array (
                'id' => 55000203,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901101',
                'vpd' => '311110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            203 =>
            array (
                'id' => 55000204,
                'execsfsituacao_id' => 55000030,
                'nd' => '31901146',
                'vpd' => '113110105',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            204 =>
            array (
                'id' => 55000205,
                'execsfsituacao_id' => 55000227,
                'nd' => '31901146',
                'vpd' => '113110105',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            205 =>
            array (
                'id' => 55000206,
                'execsfsituacao_id' => 55000008,
                'nd' => '33900809',
                'vpd' => '313110600',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            206 =>
            array (
                'id' => 55000207,
                'execsfsituacao_id' => 55000212,
                'nd' => '33900809',
                'vpd' => '313110600',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            207 =>
            array (
                'id' => 55000208,
                'execsfsituacao_id' => 55000008,
                'nd' => '33904901',
                'vpd' => '313110200',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            208 =>
            array (
                'id' => 55000209,
                'execsfsituacao_id' => 55000212,
                'nd' => '33904901',
                'vpd' => '313110200',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            209 =>
            array (
                'id' => 55000210,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901106',
                'vpd' => '321210900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            210 =>
            array (
                'id' => 55000211,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901106',
                'vpd' => '321210900',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            211 =>
            array (
                'id' => 55000212,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901131',
                'vpd' => '311110400',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            212 =>
            array (
                'id' => 55000213,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901131',
                'vpd' => '311110400',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            213 =>
            array (
                'id' => 55000214,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901174',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            214 =>
            array (
                'id' => 55000215,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901174',
                'vpd' => '321110100',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            215 =>
            array (
                'id' => 55000216,
                'execsfsituacao_id' => 55000006,
                'nd' => '31901136',
                'vpd' => '321110300',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            216 =>
            array (
                'id' => 55000217,
                'execsfsituacao_id' => 55000211,
                'nd' => '31901136',
                'vpd' => '321110300',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            217 =>
            array (
                'id' => 55000218,
                'execsfsituacao_id' => 55000099,
                'nd' => '0',
                'vpd' => '1661',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            218 =>
            array (
                'id' => 55000219,
                'execsfsituacao_id' => 55000099,
                'nd' => '0',
                'vpd' => '1717',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            219 =>
            array (
                'id' => 55000220,
                'execsfsituacao_id' => 55000094,
                'nd' => '0',
                'vpd' => '561',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            220 =>
            array (
                'id' => 55000221,
                'execsfsituacao_id' => 55000152,
                'nd' => '0',
                'vpd' => '218810199',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            221 =>
            array (
                'id' => 55000222,
                'execsfsituacao_id' => 55000111,
                'nd' => '0',
                'vpd' => '2402',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            222 =>
            array (
                'id' => 55000223,
                'execsfsituacao_id' => 55000006,
                'nd' => '31909401',
                'vpd' => '311110800',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            223 =>
            array (
                'id' => 55000224,
                'execsfsituacao_id' => 55000211,
                'nd' => '31909401',
                'vpd' => '311110800',
                'ddp_nivel' => 'A',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            224 =>
            array (
                'id' => 55000225,
                'execsfsituacao_id' => 55000029,
                'nd' => '31901145',
                'vpd' => '113110102',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            225 =>
            array (
                'id' => 55000226,
                'execsfsituacao_id' => 55000226,
                'nd' => '31901145',
                'vpd' => '113110102',
                'ddp_nivel' => 'B',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            226 =>
            array (
                'id' => 55000227,
                'execsfsituacao_id' => 55000008,
                'nd' => '33903628',
                'vpd' => '313119900',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            227 =>
            array (
                'id' => 55000228,
                'execsfsituacao_id' => 55000212,
                'nd' => '33903628',
                'vpd' => '313119900',
                'ddp_nivel' => 'E',
                'status' => true,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));


    }
}
